{
    "0": "Znak Świetlika „Meteor na Ziemi”",
    "1": "Znak Świetlika „Kometa na Ziemi”",
    "2": "Znak Lampy „Fenomen Świetlika”",
    "4": "Znak Lampy „Fenomen Świetlika”",
    "5": "Znak Lampy „Fenomen Świetlika”",
    "6": "Znak Wicia „Mały Owad”",
    "7": "Znak Wicia „Burza Małych Owadów”",
    "8": "Znak Wicia „Burza Nocnych Owadów”",
    "9": "Znak Wicia „Tornado Nocnych Owadów”",
    "10": "Ukryty Owad „Odosobnienie Nieskończonej Nocy”",
    "11": "Ukryty Owad „Odosobnienie Nieskończonej Nocy”",
    "12": "Ukryty Owad „Odosobnienie Nieskończonej Nocy”",
    "13": "Znak Wokalu „Pohukiwanie w Nocy”",
    "14": "Znak Wokalu „Pohukiwanie w Nocy”",
    "15": "Znak Wokalu „Skowyt Puchacza”",
    "16": "Znak Wokalu „Skowyt Puchacza”",
    "3": "Znak Lampy „Fenomen Świetlika”",
    "54": "Znak Marzeń „Podwójna Bariera”",
    "55": "Znak Marzeń „Podwójna Bariera”",
    "56": "Kraina Marzeń „Super Podwójna Bariera”",
    "57": "Kraina Marzeń „Super Podwójna Bariera”",
    "58": "Znak Duszy „Pieczęć Marzeń -Rozrzut-”",
    "59": "Znak Duszy „Pieczęć Marzeń -Rozrzut-”",
    "60": "Rozproszona Dusza „Pieczęć Marzeń -Zużyta-”",
    "61": "Rozproszona Dusza „Pieczęć Marzeń -Zużyta-”",
    "62": "Znak Marzeń „Krąg Pieczętujący Zło”",
    "63": "Znak Marzeń „Krąg Pieczętujący Zło”",
    "64": "Boska Sztuka „Wielokierunkowy Krąg Wiążący Oni”",
    "65": "Boska Sztuka „Wielokierunkowy Krąg Uśmiercający Smoki”",
    "66": "Znak Duszy „Pieczęć Marzeń -Koncentracja-”",
    "67": "Znak Duszy „Pieczęć Marzeń -Koncentracja-”",
    "70": "Granica „Podwójna Bariera Danmaku”",
    "71": "Granica „Podwójna Bariera Danmaku”",
    "72": "Wielka Bariera „Bariera Danmaku Hakurei”",
    "73": "Wielka Bariera „Bariera Danmaku Hakurei”",
    "74": "Boska Dusza „Pieczęć Marzeń -Mignięcie-”",
    "75": "Boska Dusza „Pieczęć Marzeń -Mignięcie-”",
    "76": "Boska Dusza „Pieczęć Marzeń -Mignięcie-”",
    "77": "Znak Magii „Droga Mleczna”",
    "78": "Znak Magii „Droga Mleczna”",
    "79": "Magiczna Przestrzeń „Pas Planetoid”",
    "80": "Magiczna Przestrzeń „Pas Planetoid”",
    "81": "Znak Magii „Zaduma Gwiezdnego Pyłu”",
    "82": "Znak Magii „Zaduma Gwiezdnego Pyłu”",
    "83": "Czarna Magia „Horyzont Zdarzeń”",
    "84": "Czarna Magia „Horyzont Zdarzeń”",
    "85": "Znak Miłości „Bezkierunkowy Laser”",
    "86": "Znak Miłości „Bezkierunkowy Laser”",
    "87": "Burza Miłości „Tajfun Światła Gwiazd”",
    "88": "Burza Miłości „Tajfun Światła Gwiazd”",
    "89": "Znak Miłości „Mistrzowska Iskra”",
    "90": "Znak Miłości „Mistrzowska Iskra”",
    "91": "Kochające Serce „Podwójna Iskra”",
    "92": "Kochające Serce „Podwójna Iskra”",
    "93": "Znak Światła „Promień Światła Ziemskiego”",
    "94": "Znak Światła „Promień Światła Ziemskiego”",
    "95": "Rozbłysk Światła „Zestrzelić Księżyc”",
    "96": "Rozbłysk Światła „Zestrzelić Księżyc”",
    "97": "Magiczne Działo „Ostateczna Iskra”",
    "98": "Magiczne Działo „Ostateczna Iskra”",
    "99": "Magiczne Działo „Ostateczna Mistrzowska Iskra”",
    "191": "Przeszłość „Stara Historia Dziewiczej Krainy -Dawna Historia-”",
    "136": "Klątwa Niebios „Apollo 13”",
    "135": "Klątwa Niebios „Apollo 13”",
    "137": "Klątwa Niebios „Apollo 13”",
    "138": "Klątwa Niebios „Apollo 13”",
    "139": "Ezoteryka „Astronomiczne Ukrycie”",
    "140": "Ezoteryka „Astronomiczne Ukrycie”",
    "141": "Ezoteryka „Astronomiczne Ukrycie”",
    "142": "Ezoteryka „Astronomiczne Ukrycie”",
    "143": "Zakazany Eliksir „Eliksir Hourai”",
    "144": "Zakazany Eliksir „Eliksir Hourai”",
    "145": "Zakazany Eliksir „Eliksir Hourai”",
    "146": "Zakazany Eliksir „Eliksir Hourai”",
    "195": "Nieśmiertelny „Ptak Ognia -Wzbicie Fenga-”",
    "196": "Fujiwara „Rany Świątyni Metsuzai”",
    "197": "Nieśmiertelny „Wymiar Xu Fu”",
    "198": "Pokuta „Śmierć Uczciwego Człowieka”",
    "200": "Niewygasły „Ogon Feniksa”",
    "201": "Hourai „Piękna Pogoda przy Południowym Wietrze -Wulkan Fujiyama-”",
    "202": "„Opętanie przez Feniksa”",
    "203": "„Lalka Hourai”",
    "112": "Znak Rozrzutu „Księżyc Prawdy (Niewidzialna Pełnia Księżyca)”",
    "113": "Znak Rozrzutu „Księżyc Prawdy (Niewidzialna Pełnia Księżyca)”",
    "114": "Znak Rozrzutu „Księżyc Prawdy (Niewidzialna Pełnia Księżyca)”",
    "115": "Znak Rozrzutu „Księżyc Prawdy (Niewidzialna Pełnia Księżyca)”",
    "17": "Znak Ćmy „Owadzia Klątwa Zawisakowatych”",
    "18": "Znak Ćmy „Owadzia Klątwa Zawisakowatych”",
    "19": "Toksyczny Znak „Łuski Trującej Ćmy”",
    "20": "Zabójcza Toksyna „Taniec w Mroku Trującej Ćmy”",
    "21": "Znak Jastrzębia „Pechowe Nurkowanie”",
    "22": "Znak Jastrzębia „Pechowe Nurkowanie”",
    "23": "Znak Jastrzębia „Pechowe Nurkowanie”",
    "24": "Znak Jastrzębia „Pechowe Nurkowanie”",
    "25": "Kurza Ślepota „Śpiew Nocnego Wróbla”",
    "26": "Kurza Ślepota „Śpiew Nocnego Wróbla”",
    "27": "Kurza Ślepota „Śpiew Nocnego Wróbla”",
    "28": "Kurza Ślepota „Śpiew Nocnego Wróbla”",
    "29": "Nocny Wróbel „Chórmistrz Północy”",
    "30": "Nocny Wróbel „Chórmistrz Północy”",
    "31": "Nocny Wróbel „Chórmistrz Północy”",
    "32": "Duchowe Narodzenie „Pierwsza Piramida”",
    "33": "Duchowe Narodzenie „Pierwsza Piramida”",
    "34": "Duchowe Narodzenie „Pierwsza Piramida”",
    "35": "Duchowe Narodzenie „Pierwsza Piramida”",
    "36": "Znak Pochodzenia „Ulotność 137”",
    "37": "Znak Pochodzenia „Ulotność 137”",
    "38": "Znak Pochodzenia „Ulotność 137”",
    "39": "Znak Ambicji „Kryzys Buretsu”",
    "40": "Znak Ambicji „Kryzys Masakado”",
    "41": "Znak Ambicji „Kryzys Yoshimitsu”",
    "42": "Znak Ambicji „Kryzys Kwatery Głównej”",
    "43": "Znak Ziemi „Trzy Święte Skarby - Miecz”",
    "44": "Znak Ziemi „Trzy Święte Skarby - Kula”",
    "45": "Znak Ziemi „Trzy Święte Skarby - Zwierciadło”",
    "46": "Schemat Ziemi „Trzy Święte Skarby - Kraj”",
    "47": "Znak Końca „Urojony Cesarz”",
    "48": "Znak Końca „Urojony Cesarz”",
    "49": "Pseudohistoria „Legenda Gensokyo”",
    "50": "Pseudohistoria „Legenda Gensokyo”",
    "51": "Przyszłość „Wysoka Równina Niebios”",
    "53": "Przyszłość „Wysoka Równina Niebios”",
    "52": "Przyszłość „Wysoka Równina Niebios”",
    "68": "Migrujący Duch „Pieczęć Marzeń -Niedoskonałość-”",
    "69": "Migrujący Duch „Pieczęć Marzeń -Niedoskonałość-”",
    "100": "Znak Fali „Czerwonooka Hipnoza (Mieszacz Umysłów)”",
    "101": "Znak Fali „Czerwonooka Hipnoza (Mieszacz Umysłów)”",
    "102": "Znak Fali „Czerwonooka Hipnoza (Szokowanie)”",
    "103": "Znak Fali „Czerwonooka Hipnoza (Szokowanie)”",
    "104": "Obłąkany Znak „Strojenie Halucynogenne (Strojenie Wizji)”",
    "105": "Obłąkany Znak „Strojenie Halucynogenne (Strojenie Wizji)”",
    "106": "Obłąkane Spojrzenie „Strojenie Obłąkanego Spojrzenia (Poszukiwacz Iluzji)”",
    "107": "Obłąkane Spojrzenie „Strojenie Obłąkanego Spojrzenia (Poszukiwacz Iluzji)”",
    "108": "Znak Leniwca „Zatrzymanie Życia i Duszy (Bezczynna Fala)”",
    "109": "Znak Leniwca „Zatrzymanie Życia i Duszy (Bezczynna Fala)”",
    "110": "Indolencja „Zatrzymanie Życia i Duszy (Zatrzymanie Umysłu)”",
    "111": "Indolencja „Zatrzymanie Życia i Duszy (Zatrzymanie Umysłu)”",
    "116": "Księżycowe Oczy „Zdalny Mesmeryzm Księżycowego Królika (Telemesmeryzm)”",
    "117": "Księżycowe Oczy „Zdalny Mesmeryzm Księżycowego Królika (Telemesmeryzm)”",
    "118": "Księżycowe Oczy „Zdalny Mesmeryzm Księżycowego Królika (Telemesmeryzm)”",
    "119": "Sfera Kosmiczna „Świat w Naczyniu”",
    "120": "Sfera Kosmiczna „Świat w Naczyniu”",
    "121": "Sfera Kosmiczna „Świat w Naczyniu”",
    "122": "Sfera Kosmiczna „Świat w Naczyniu”",
    "123": "Przebudzony Bóg „Wspomnienia z Ery Bogów”",
    "124": "Przebudzony Bóg „Wspomnienia z Ery Bogów”",
    "125": "Boski Znak „Genealogia Niebiańskich”",
    "126": "Boski Znak „Genealogia Niebiańskich”",
    "127": "Wskrzeszenie „Seimei Yūgi -Gra w Życie-”",
    "128": "Wskrzeszenie „Seimei Yūgi -Gra w Życie-”",
    "129": "Zmartwychwstanie „Gra Powstania”",
    "130": "Zmartwychwstanie „Gra Powstania”",
    "131": "Wiodący Bóg „Narzędzie Omoikane”",
    "132": "Wiodący Bóg „Narzędzie Omoikane”",
    "133": "Boski Umysł „Mózg Omoikane”",
    "134": "Boski Umysł „Mózg Omoikane”",
    "147": "Znak Medycyny „Supergalaktyka w Naczyniu”",
    "148": "Znak Medycyny „Supergalaktyka w Naczyniu”",
    "149": "Znak Medycyny „Supergalaktyka w Naczyniu”",
    "150": "Znak Medycyny „Supergalaktyka w Naczyniu”",
    "151": "Niemożliwe Żądanie „Klejnot z Szyi Smoka -Pięciokolorowe Pociski-”",
    "152": "Niemożliwe Żądanie „Klejnot z Szyi Smoka -Pięciokolorowe Pociski-”",
    "153": "Boski Skarb „Olśniewający Pocisk Smoka”",
    "154": "Boski Skarb „Olśniewający Pocisk Smoka”",
    "155": "Niemożliwe Żądanie „Kamienna Misa Buddy -Nieugięta Wola-”",
    "156": "Niemożliwe Żądanie „Kamienna Misa Buddy -Nieugięta Wola-”",
    "157": "Boski Skarb „Buddyjski Diament”",
    "158": "Boski Skarb „Buddyjski Diament”",
    "159": "Niemożliwe Żądanie „Płaszcz z Ognistego Szczura -Cierpliwy Umysł-”",
    "160": "Niemożliwe Żądanie „Płaszcz z Ognistego Szczura -Cierpliwy Umysł-”",
    "161": "Boski Skarb „Tarcza Salamandry”",
    "162": "Boski Skarb „Tarcza Salamandry”",
    "163": "Niemożliwe Żądanie „Jaskółcza Muszla Porcelanki -Wieczne Życie-”",
    "164": "Niemożliwe Żądanie „Jaskółcza Muszla Porcelanki -Wieczne Życie-”",
    "165": "Boski Skarb „Nieskończone Źródło Życia”",
    "166": "Boski Skarb „Nieskończone Źródło Życia”",
    "167": "Niemożliwe Żądanie „Gałąź Pocisków Hourai -Tęczowe Danmaku-”",
    "168": "Niemożliwe Żądanie „Gałąź Pocisków Hourai -Tęczowe Danmaku-”",
    "169": "Boski Skarb „Klejnotowa Gałąź Hourai -Senny Raj-”",
    "170": "Boski Skarb „Klejnotowa Gałąź Hourai -Senny Raj-”",
    "171": "„Koniec Nieprzemijającej Nocy -Nów-”",
    "172": "„Koniec Nieprzemijającej Nocy -Półksiężyc-”",
    "173": "„Koniec Nieprzemijającej Nocy -Pierwsza Kwadra-”",
    "174": "„Koniec Nieprzemijającej Nocy -Matsuyoi-”",
    "175": "„Koniec Nieprzemijającej Nocy -Godzina Szczura-”",
    "176": "„Koniec Nieprzemijającej Nocy -Wpół do Północy-”",
    "177": "„Koniec Nieprzemijającej Nocy -Północ-”",
    "178": "„Koniec Nieprzemijającej Nocy -Wpół do Pierwszej-”",
    "179": "„Koniec Nieprzemijającej Nocy -Godzina Woła-”",
    "180": "„Koniec Nieprzemijającej Nocy -Wpół do Drugiej-”",
    "181": "„Koniec Nieprzemijającej Nocy -Środek Nocy-”",
    "182": "„Koniec Nieprzemijającej Nocy -Wpół do Trzeciej-”",
    "183": "„Koniec Nieprzemijającej Nocy -Godzina Tygrysa-”",
    "184": "„Koniec Nieprzemijającej Nocy -Wpół do Czwartej-”",
    "185": "„Koniec Nieprzemijającej Nocy -Czwarta-”",
    "186": "„Koniec Nieprzemijającej Nocy -Wpół do Piątej-”",
    "187": "„Koniec Nieprzemijającej Nocy -Poranna Mgła-”",
    "188": "„Koniec Nieprzemijającej Nocy -Świt-”",
    "189": "„Koniec Nieprzemijającej Nocy -Jutrzenka-”",
    "190": "„Koniec Nieprzemijającej Nocy -Budzący się Świat-”",
    "192": "Reinkarnacja „Most Powrotu Ichijou”",
    "193": "Przyszłość „Nowa Historia Fantazji -Następna Historia-”",
    "194": "Przedawnienie „Klątwa Tsuki-no-Iwakasy”",
    "199": "Pusta Istota „Wu”",
    "204": "„Nieprzemijający Ostrzał”",
    "205": "„Niesezonowy Sztorm Motyli”",
    "206": "„Ślepy Nocny Ptak”",
    "207": "„Cesarz Kraju Kwitnącej Wiśni”",
    "208": "„Spojrzenie Mglistego Widmowego Księżyca (Szalone Czerwone Oczy)”",
    "209": "„Sieć Łapiąca Motyle Niebiańskiego Pająka”",
    "210": "„Morze Drzew Hourai”",
    "211": "„Odrodzenie Feniksa”",
    "212": "„Starożytny Oszust”",
    "213": "„Pełne Oczyszczenie”",
    "215": "„Płonąca Gwiazda”",
    "216": "„Świat Deflacji”",
    "217": "„Cięcie Satelity Odbijające Matsuyoi”",
    "218": "„Upiór w Grand Guignol”",
    "219": "„Szkarłatny Los”",
    "220": "„Parinirwana Saigyouji”",
    "221": "„Głęboka Bariera Danmaku -Marzenia, Złudzenia, Bańki i Cienie-”",
    "214": "„Wrodzone Marzenie”"
}