{
    "1": "Znak Duszy „Fantazyjna Pieczęć”",
    "11": "Znak Magii \"Zaduma Gwiezdnego Pyłu\"",
    "50": "Znak Mrozu „Idealny Mróz”",
    "0": "Znak Duszy „Znak Yin-Yang”",
    "2": "Znak Duszy „Iluzja Hakurei”",
    "10": "Znak Magii „Gwiezdny Pył”",
    "12": "Znak Magii „Gwiazda Iluzji”",
    "20": "Znak Czasu „Prywatna Wizja”",
    "22": "Znak Czasu „Tajemniczy Kuba”",
    "30": "Znak Wahań „Miecz Wiążących Pragnień”",
    "40": "Znak Fali „Księżycowa Zmarszczka (Fala Selenicka)”",
    "42": "Znak Rozproszenia „Marzenie Dobrobytu (Selenickie Megalopolis)”",
    "52": "Znak Mrozu „Zimna Boskość”",
    "60": "Znak Hałasu „Przepływ Hałasu Duszy”",
    "62": "Znak Hałasu „Solówka Lyrici Na Żywo”",
    "70": "Znak Ptaka „Ludzka Klatka”",
    "71": "Znak Ptaka „Podwójna Ludzka Klatka”",
    "72": "Znak Ptaka „Tajemnicza Pieśń”",
    "80": "Znak Królika „Wielki Herb Pomyślności”",
    "82": "Znak Królika „Biały Królik z Inaby”",
    "90": "Znak Kwiatów „Zakwitanie Gensokyo”",
    "92": "Fantazja „Naturalne Piękna”",
    "100": "Znak Wiatru „Wachlarz Boga Wiatru”",
    "102": "Podmuch „Młoda Bogini Wiatru”",
    "110": "Znak Trucizny „Trucizna Nerwowa”",
    "112": "Znak Trucizny „Trucizna Na Melancholię”",
    "122": "Shinigami „Do Higan i z Powrotem”",
    "130": "Znak Winy „Włóczący Się Grzech”",
    "132": "Osąd „Sąd Ostateczny”",
    "32": "Znak Wahań „Oświecenie Półciała”",
    "150": "Znak Hałasu „Melancholia Hałasu”",
    "152": "Znak Hałasu „Solówka Lunasy Na Żywo”",
    "120": "Napiwek „Wczorajsze Pieniądze”",
    "142": "Znak Hałasu „Radość Merlin Na Żywo”",
    "140": "Znak Hałasu „Radość Dusz”"
}