{
    "th07 Menu Start": "Rozpocznij rozgrywkę",
    "th07 Menu Extra Start": "Rozpocznij poziom Extra",
    "th07 Menu Practice Start": "Wybierz poziom i rozpocznij trening",
    "th07 Menu Music Room": "Rozkosz się muzyką",
    "th07 Menu Replay": "Obejrzyj powtórki",
    "th07 Menu Option": "Zmień opcje",
    "th07 Menu Quit": "Wyjdź z gry",
    "th06 Bomb Reimu B": "Znak Marzeń „Krąg Pieczętujący Zło”",
    "th06 Bomb Marisa A": "Znak Magii „Zaduma Gwiezdnego Pyłu”",
    "th06 Bomb Marisa B": "Znak Miłości „Mistrzowska Iskra”",
    "th07 Bomb Reimu A unfocused": "Znak Duszy „Pieczęć Marzeń -Rozrzut-”",
    "th07 Bomb Reimu A focused": "Znak Duszy „Pieczęć Marzeń -Koncentracja-”",
    "th07 Bomb Reimu B focused": "Znak Marzeń „Podwójna Bariera”",
    "th07 Bomb Marisa A focused": "Znak Magii „Droga Mleczna”",
    "th07 Bomb Marisa B unfocused": "Znak Miłości „Bezkierunkowy Laser”",
    "th07 Bomb Sakuya A unfocused": "Znak Iluzji „Niewybredność”",
    "th07 Bomb Sakuya A focused": "Znak Iluzji „Lalka Zabójczyni”",
    "th10 Music Room spoiler 1": "<c$** Wybrany przez ciebie utwór nie został jeszcze odegrany podczas gry **$>",
    "th10 Music Room spoiler 2": "<c$Jego komentarz może zawierać spoilery.$>",
    "th10 Music Room spoiler 3": "<c$Pomimo tego chcesz posłuchać tej ścieżki?$>",
    "th10 Music Room spoiler 4": "<c$Jeśli tak, wciśnij jeszcze raz klawisz strzału.$>",
    "th10 Music Room spoiler 5": "<c$Jeśli nie, proszę wybrać inny utwór.$>",
    "th13 spell nothing": "Nic...",
    "th10 Dialog Prompt": "Proszę wybrać tryb okienkowy",
    "th10 Dialog Fullscreen": "Pełny ekran",
    "th10 Dialog Always ask": "Zawsze pytaj",
    "th11 Dialog Fullscreen 640": "Pełny ekran (640x480)",
    "th11 Dialog Window 640": "Tryb okienkowy (640x480)",
    "th11 Dialog Window 960": "Tryb okienkowy (960x720)",
    "th11 Dialog Window 1280": "Tryb okienkowy (1280x960)",
    "th11 Dialog Game Start": "Start",
    "th14 Dialog Prompt": "Proszę wybrać rozdzielczość",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720",
    "th14 Dialog 1280": "1280x960 (zalecany)",
    "th14 Dialog Fullscreen": "Uruchom w trybie pełnoekranowym",
    "th14 Dialog Always ask": "Zawsze pytaj",
    "th10 JP": "Touhou Fuujinroku ~ Mountain of Faith",
    "alcostg JP": "Uwabami Breakers",
    "th11 JP": "Touhou Chireiden ~ Subterranean Animism",
    "th12 JP": "Touhou Seirensen ~ Undefined Fantastic Object",
    "th125 JP": "Double Spoiler",
    "th128 JP": "Yousei Daisensho ~ Fairy Wars",
    "th13 JP": "Touhou Shinreibyou ~ Ten Desires",
    "th14 JP": "Touhou Kishinjou ~ Double Dealing Character",
    "th06 32bits mode": "32 bity",
    "th06 16bits mode": "16 bitów",
    "th06 cancel": "Anuluj",
    "th10_ascii_stage_1": "Poziom 1",
    "th10_ascii_stage_2": "Poziom 2",
    "th10_ascii_stage_3": "Poziom 3",
    "th10_ascii_stage_4": "Poziom 4",
    "th10_ascii_stage_5": "Poziom 5",
    "th10_ascii_stage_6": "Poziom 6",
    "th10_ascii_stage_clear": "Sukces",
    "th14_ascii_no_bonus": "BEZ BONUSU",
    "th14_ascii_bonus": "BONUS %.1f",
    "th13_ascii_spell_game": "TRYB GRY         %4d/%4d",
    "th13_ascii_spell_unknown": "WYNIK        00  ----/----",
    "th13_ascii_spell_score": "WYNIK %8d0  %4d/%4d",
    "th10_ascii_score_empty": "%2d  %s  %9ld%d  ----/--/-- --:--  Poziom -  ---%",
    "th10_ascii_ranking": "           Lista Wynikow!!",
    "th13_ascii_credit": "Napisy %d",
    "th08 Option BGM Volume": "Zmień głośność muzyki.",
    "th08 Option SE Volume": "Zmień głośność efektów dźwiękowych.",
    "th06 Bomb Reimu A": "Znak Duszy „Pieczęć Marzeń”",
    "th08 Bomb Reimu": "Znak Duszy „Kula Marzeń”",
    "th08 Bomb Reimu Last": "Boska Dusza „Pieczęć Marzeń -Mignięcie-”",
    "th08 Bomb Yukari": "Znak Granicy „Poczwórna Bariera”",
    "th08 Bomb Yukari Last": "Granica „Poczwórna Bariera Nieprzemijającej Nocy”",
    "th08 Bomb Marisa Last": "Magiczne Działo „Ostateczna Iskra”",
    "th08 Bomb Alice": "Znak Magii „Zmyślna Ofiara”",
    "th08 Bomb Sakuya Last": "Iluzyjny Pogrzeb „Fantomowy Morderca w Nocnej Mgle”",
    "th08 Spell Resurrection": "„Odrodzenie”",
    "th06 config": "Touhou Koumakyou - Konfiguracja",
    "th06 up": "Góra ",
    "th06 down": "Dół ",
    "th06 left": "Lewo ",
    "th06 right": "Prawo ",
    "th06 vertex": "Wyłącz vertex buffer",
    "th06 fog": "Wyłącz mgłę",
    "th06 16bit textures": "Tylko 16-bitowe tekstury",
    "th06 Gouraud shading": "Ogranicz cieniowanie Gourauda",
    "th06 color composition": "Wyłącz komponowanie kolorów tekstur",
    "th06 rasterizer mode": "Rozpocznij grę w trybie rasteryzatora referencyjnego",
    "th06 clear buffer": "Wyczyść dane back buffera podczas odświeżania",
    "th06 minimum graphics": "Wyświetl grafikę minimalną",
    "th06 depth test": "Wyłącz test głębi",
    "th06 force frame": "Wymuś 60 klatek na sekundę",
    "th06 fullscreen": "Pełny ekran",
    "th06 windowed": "Tryb okienkowy",
    "th06 full rate": "1/1 (domyślnie)",
    "th06 half rate": "1/2",
    "th06 third rate": "1/3",
    "th06 accept": "OK",
    "th06 screen mode": "Rozmiar okna",
    "th06 refresh rate": "Pomijanie klatek",
    "th06 colors": "Głębia koloru",
    "th06 pad X axis": "Pad: Oś X (1-1000)",
    "th06 pad Y axis": "Pad: Oś Y (1-1000)",
    "th06 check pad": "Testuj pad kierunkowy",
    "th06 config saved caption": "OK",
    "th06 config saved text": "Konfiguracja zapisana.",
    "DirectInput fix": "Używaj DirectInput",
    "th07 Menu Result": "Zobacz wyniki i karty zaklęć",
    "th07 Option Player": "Wybierz początkową liczbę żyć. (Domyślnie: 3)",
    "th07 Option Graphic": "Zmień głębię koloru ekranu. Wersja 32-bitowa wygląda najlepiej.",
    "th07 Option BGM": "Wybierz tryb muzyki. (Domyślnie: WAV)",
    "th07 Key Reset": "Przywróć domyślne ustawienia sterowania.",
    "th08 Bomb Remilia Last": "Szkarłatna Magia „Szkarłatny Diabeł”",
    "th08 Bomb Yuyuko": "Znak Śmierci „Upiorny Sen”",
    "th08 Bomb Yuyuko Last": "Motyl Śmierci „Wieczny Sen w Krainie Marzeń”",
    "th08 Bomb Alice Last": "Magiczna Manipulacja „Powrót Nieożywionych”",
    "th08 Spell Dissolve": "„Likwidacja Zaklęcia”",
    "DirectInput fix, layout-dependent shot key": "Używaj DirectInput (Klawisz strzału: %c)",
    "th08 Bomb Remilia": "Znak Szkarłatu „Czerwień, Bezsenny Zamek”",
    "th08 Bomb Youmu": "Znak Człowieka „Cięcie Współczesnego Świata”",
    "th08 Bomb Youmu Last": "Człowiek Oni „Cięcie Wiecznej Przyszłości”",
    "th07 Bomb Sakuya B unfocused": "Znak Czasu „Perfekcyjny Kwadrat”",
    "th07 Bomb Sakuya B focused": "Znak Czasu „Prywatny Kwadrat”",
    "th08 Menu Spell Practice": "Przećwicz karty zaklęć przeciwników.",
    "th07 Option Quit": "Wyjdź z ustawień.",
    "th07 Option Key Config": "Skonfiguruj sterowanie.",
    "th07 Option Reset": "Przywróć domyślne ustawienia.",
    "th07 Option Window Mode": "Wybierz tryb pełnoekranowy lub tryb okienkowy.",
    "th07 Option Sound": "Włącz lub wyłącz efekty dźwiękowe.",
    "th07 Option Slow Mode": "Spowolnij grę przy dużej ilości pocisków. (Wyłącza to rekordy i powtórki!)",
    "th07 Key Shot": "Ustaw klawisz strzału/potwierdzenia.",
    "th07 Key Bomb": "Ustaw klawisz bomby/anulowania.",
    "th07 Key Slow": "Ustaw klawisz spowolnionego ruchu.",
    "th07 Key Skip": "Ustaw klawisz ominięcia tekstu.",
    "th07 Key Pause": "Ustaw klawisz pauzy.",
    "th07 Key Up": "Ustaw klawisz ruchu w górę.",
    "th07 Key Down": "Ustaw klawisz ruchu w dół.",
    "th07 Key Left": "Ustaw klawisz ruchu w lewo.",
    "th07 Key Right": "Ustaw klawisz ruchu w prawo.",
    "th07 Key ShotSlow": "Spowolnij ruch, gdy przytrzymany jest klawisz strzału.",
    "th07 Key Quit": "Wyjdź z ustawień sterowania.",
    "th07 16bits textures": "Wymuś 16-bitowe tekstury",
    "th11 default": "Przywróć wszystkie domyślne ustawienia",
    "th07 fullscreen": "Pełny ekran (zalecane)",
    "th07 32bits mode": "32-bit (domyślne)",
    "th07 VSync": "Wyłącz synchronizację pionową",
    "th07 effect quality": "Jakość efektów",
    "th07 low effects": "Niska",
    "th07 medium effects": "Średnia",
    "th07 high effects": "Wysoka (zalecane)",
    "th16_ascii_score_spring": "Wiosna",
    "th16_ascii_score_summer": "Lato",
    "th16_ascii_score_autumn": "Jesien",
    "th16_ascii_score_winter": "Zima",
    "th07 Stage Clear": "Poziom Ukonczony",
    "th07 All Clear": "Gra Ukonczona!",
    "th07 Clear Point Items Format": "Punkty = %8d",
    "th07 Clear Graze Format": "Otarcia= %8d",
    "th07 Clear Cherry Format": "Wisnie = %8d",
    "th07 Clear Bonus Life Format": "Zycia  =%9d",
    "th07 Clear Bonus Bomb Format": "Bomby  = %8d",
    "th07 Clear Easy Multiplier": "Tryb Latwy   *0.5",
    "th07 Clear Normal Multiplier": "Tryb Normalny*1.0",
    "th07 Clear Hard Multiplier": "Tryb Trudny  *1.2",
    "th07 Clear Lunatic Multiplier": "Tryb Szalony *1.5",
    "th07 Clear Extra Multiplier": "Poziom Extra *2.0",
    "th07 Clear Phantasm Multiplier": "Poziom Phantasm*2.0",
    "th07 Clear Player Penalty*0.5": "Kara Zyc      *0.5",
    "th07 Clear Player Penalty*0.2": "Kara Zyc      *0.2",
    "th07 Clear Player Penalty*0.1": "Kara Zyc      *0.1",
    "th07 Clear Player Penalty*0.05": "Kara Zyc      *0.05",
    "th07 Clear Total Score Format": "Suma  = %8d0",
    "th08 Clear Time Orbs Format": "Czas  = %8d0",
    "th08 Clear Last Time Format": "Ostatni Czas = %2d:%.2d",
    "th08 Clear Night Bonus": "Bonus Nocy",
    "th06_ascii_centered_stage": "POZIOM %d",
    "th06_ascii_centered_stage_final": "OSTATNI POZIOM",
    "th06_ascii_centered_stage_extra": "POZIOM EXTRA",
    "th06_ascii_centered_spell_bonus": "Bonus Karty Zaklecia!",
    "th06_ascii_fullpower": "Pelna Moc!!",
    "th06_ascii_bonus_format": "BONUS %8d",
    "th06_ascii_clear_header": "Poziom Ukonczony",
    "th06_ascii_clear_header_all": "Gra Ukonczona!",
    "th06_ascii_clear_bonus_stage": "Poziom * 1000 = %5d",
    "th06_ascii_clear_bonus_power": "Moc *    100 = %5d",
    "th06_ascii_clear_bonus_graze": "Otarcia * 10 = %5d",
    "th06_ascii_clear_bonus_player": "Zycia     = %8d",
    "th06_ascii_clear_bonus_bomb": "Bomby     = %8d",
    "th06_ascii_clear_bonus_easy": "Tryb Latwy     * 0.5",
    "th06_ascii_clear_bonus_normal": "Tryb Normalny  * 1.0",
    "th06_ascii_clear_bonus_hard": "Tryb Trudny    * 1.2",
    "th06_ascii_clear_bonus_lunatic": "Tryb Szalony   * 1.5",
    "th06_ascii_clear_bonus_extra": "Poziom Extra   * 2.0",
    "th06_ascii_clear_bonus_penalty_0.5": "Kara Zyc       * 0.5",
    "th06_ascii_clear_bonus_penalty_0.2": "Kara Zyc       * 0.2",
    "th06_ascii_clear_bonus_total": "Suma      = %8d",
    "th06_ascii_replay_header": "Nr    Nazwa     Data     Postac   Tryb",
    "th06_ascii_replay": "%s %8s  %8s %-7s  %-7s",
    "th06_ascii_replay_save_header": "Nr    Nazwa    Data     Postac   Wynik",
    "th06_ascii_replay_save_empty": "Nr %.2d -------- --/--/-- -------          0",
    "th06_ascii_replay_save": "Nr %.2d %8s %8s %7s %10d",
    "th06_ascii_2_digit_number_format": "Nr %2d",
    "th06_ascii_replay_user": "Gracz",
    "th06_ascii_easy": "Latwy",
    "th06_ascii_normal": "Normalny",
    "th06_ascii_hard": "Trudny",
    "th06_ascii_lunatic": "Szalony",
    "th06_ascii_replay_stage_header": "Poziom  Koncowy Wynik",
    "th06_ascii_replay_stage_1": "Poziom1",
    "th06_ascii_replay_stage_2": "Poziom2",
    "th06_ascii_replay_stage_3": "Poziom3",
    "th06_ascii_replay_stage_4": "Poziom4",
    "th06_ascii_replay_stage_5": "Poziom5",
    "th06_ascii_replay_stage_6": "Poziom6",
    "th07 MAX": "MAKS",
    "th07 Clear Bonus Format": "Poziom = %8d",
    "th07 Stats Header Easy": "Łatwy",
    "th07 CherryPoint Max": "Punkty Wisni Pelne!",
    "th07 Stats Header Normal": "Normalny",
    "th07 Stats Header Hard": "Trudny",
    "th07 Stats Header Lunatic": "Szalony",
    "th07 Stats Header Phantasm": "Phantasm",
    "th07 Supernatural Border": "Nadprzyrodzona Granica!!",
    "th07 Border Bonus Format": "Bonus Granicy %7d",
    "th06 Stats MarisaA": "Marisa Kirisame (Magia)",
    "th06 Stats ReimuA": "Reimu Hakurei (Dusza)",
    "th06 Stats MarisaB": "Marisa Kirisame (Miłość)",
    "th06 Stats ReimuB": "Reimu Hakurei (Marzenie)",
    "th07 Stats SakuyaA": "Sakuya Izayoi (Iluzja)",
    "th07 Stats SakuyaB": "Sakuya Izayoi (Czas)",
    "th07 Stats Total (All Characters)": "Wszystkie Postacie",
    "th07 Stats Time Since Startup": "<tl$Czas od Uruchomienia>  %.2d:%.2d:%.2d",
    "th07 Stats Total Playtime": "<l$Łączny czas gry>  %.2d:%.2d:%.2d",
    "th07 Stats Play Count": "<tl$Liczba gier\t$Reimu Hakurei (Dusza)\t $Reimu Hakurei (Sen)\t $Marisa Kirisame (Magia)\t $Marisa Kirisame (Miłość)\t $Sakuya Izayoi (Iluzja)\t $Sakuya Izayoi (Czas)\t> Łatw\t Norm\t Trud\t Szal\t Extra\t Suma",
    "th07 Stats Play Count +Phantasm": "<tl$Liczba gier\t\t\t\t\t\t\t\t\t\t\t> Łatw\t Norm\t Trud\t Szal\t Extra\t Phantas\t Suma",
    "th07 Stats Clear Count": "<tl$Liczba Ukończeń\t\t\t\t\t\t\t\t\t\t\t> %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Clear Count +Phantasm": "<tl$Liczba Ukończeń\t$Reimu Hakurei (Dusza)\t $Reimu Hakurei (Sen)\t $Marisa Kirisame (Magia)\t $Marisa Kirisame (Miłość)\t $Sakuya Izayoi (Iluzja)\t $Sakuya Izayoi (Czas)\t> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Continue": "<l$Kontynuacje> %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Continue +Phantasm": "<l$Kontynuacje> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Practice": "<l$Treningi> %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Practice +Phantasm": "<l$Treningi> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Retries": "<l$Powtórzenia> %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th07 Stats Retries +Phantasm": "<l$Powtórzenia> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
    "th16 Dialog Fullscreen": "Pełny ekran",
    "th07 config": "Touhou Youyoumu - Konfiguracja",
    "th08 config": "Touhou Eiyashou - Konfiguracja",
    "th09 config": "Touhou Kaeidzuka - Konfiguracja",
    "th095 config": "Touhou Bunkachou - Konfiguracja",
    "th10 config": "Touhou Fuujinroku - Konfiguracja",
    "th06 DirectInput": "Nie używaj pada DirectInput",
    "th16 half rate": "1/2",
    "th16 third rate": "1/3",
    "th16 refresh rate": "Pomijanie klatek",
    "th07 DirectInput": "Nie używaj DirectInput do sterowania",
    "th07 BGM memory": "Wczytuj BGM do pamięci przedwcześnie",
    "th07 draw screen": "Przerysowuj HUD co klatkę",
    "th16 default": "Przywróć wszystkie domyślne ustawienia",
    "th11 joypad sensitivity": "Czułość joypada",
    "th16 joypad sensitivity": "Czułość joypada",
    "th16 sensitivity description": "Jeśli sterowanie jest powolne, zwiększ czułość.\n(domyślne: 600)",
    "th11 always ask": "Pytaj przy każdym uruchomieniu",
    "th16 Dialog Always ask": "Pytaj przy każdym uruchomieniu",
    "th11 sensitivity description": "Jeśli sterowanie jest powolne, zwiększ czułość.\n(domyślne: 600)",
    "th07 Stats Header Total": "Suma",
    "th07 Spell Result Character Select": "%s  Suma %3d / Zdobyte %3d (Zmien Postacie↓↑)",
    "th01": "Touhou Cudowna Opowieść ~ Wysoce Czuła na Modlitwy",
    "th02": "Touhou Zapis Pieczętowania Demonów ~ Opowieść Wschodniej Krainy Czarów",
    "th03": "Touhou Sen Czasoprzestrzeni ~ Fantasmagoria Wymiarowego Snu",
    "th04": "Touhou Gensokyo ~ Opowieść Krainy Lotosu",
    "th05": "Touhou Dziwna Opowieść Romantyczna ~ Mistyczny Kwadrat",
    "th06": "Touhou Kraina Szkarłatnego Diabła ~ Wcielenie Szkarłatnego Diabła",
    "th07": "Touhou Upiorny Sen ~ Idealny Kwiat Wiśni",
    "th075": "Touhou Zbiór Marzeń ~ Niematerialna i Brakująca Moc",
    "th08": "Touhou Urywek Wiecznej Nocy ~ Nieprzemijająca Noc",
    "th09": "Touhou Kurhan Odzwierciedlający Kwiaty ~ Fantasmagoria Podziwiania Kwiatów",
    "th095": "Touhou Album Słów Kwiatów ~ Ustrzel Pocisk",
    "th10": "Touhou Kroniki Boga Wiatru ~ Góra Wiary",
    "th06_ascii_centered_stage_demo": "DEMONSTRACJA GRY",
    "th06_ascii_clear_bonus_point": "    * Punkty %3d",
    "th08 Clear Human Format": "powyzej-80%% = %3d.%.2d%%",
    "th08 Clear Youkai Format": "powyzej 80%% = %3d.%.2d%%",
    "th11": "Touhou Pałac Ziemskich Dusz ~ Podziemny Animizm",
    "th08 Spell Practice Description": "Poziom  Zdobyte/Odblokowane/W sumie(Suma postaci w nawiasach)",
    "th08 Spell Practice Percentages": "Współczynnik zdobycia (Postać/W sumie)",
    "th08 Spell Bonus Failed": "Nie Pokonano Zaklecia",
    "th08 Music Room spoiler 1": "*** UWAGA ***",
    "th08 Music Room spoiler 2": "Ten motyw jeszcze nie pojawił się w grze.",
    "th08 Music Room spoiler 3": "Jeśli nie chcesz go usłyszeć, ani nie czytać komentarza,",
    "th08 Music Room spoiler 4": "Zalecam tego unikać, jak się tylko da.",
    "th08 Music Room spoiler 6": "(Tak w ogóle, tutaj można nacisnąć OK, jak przy innych utworach,",
    "th08 Music Room spoiler 7": "aby zobaczyć komentarz i odegrać utwór, więc uważaj.)",
    "th09 Music Room spoiler 1": "***** UWAGA *****",
    "th09 Music Room spoiler 2": "Ten motyw jeszcze nie pojawił się w grze.",
    "th09 Music Room spoiler 3": "Możesz posłuchać próbki, ale tytułów utworu nie można zobaczyć.",
    "th08 Spell Result Character Select": "%3d/%3d（Zmień bohaterkę↓↑）",
    "th08 Stats Reimu & Yukari": "Reimu i Yukari",
    "th08 Stats Marisa & Alice": "Marisa i Alice",
    "th08 Stats Sakuya & Remilia": "Sakuya i Remilia",
    "th08 Stats Youmu & Yuyuko": "Youmu i Yuyuko",
    "th08 Stats Reimu": "Reimu Hakurei",
    "th08 Stats Yukari": "Yukari Yakumo",
    "th08 Stats Marisa": "Marisa Kirisame",
    "th08 Stats Alice": "Alice Margatroid",
    "th08 Stats Sakuya": "Sakuya Izayoi",
    "th08 Stats Remilia": "Remilia Scarlet",
    "th08 Stats Youmu": "Youmu Konpaku",
    "th08 Stats Yuyuko": "Yuyuko Saigyouji",
    "th08 Stats Total (All Characters)": "Wszystkie Postacie",
    "th08 Stats Time Since Startup": "<tl$Czas od uruchomienia>  %.2d:%.2d:%.2d",
    "th08 Stats Total Playtime": "<l$Łączny czas gry>  %.2d:%.2d:%.2d",
    "th08 Stats Play Count": "Liczba gier",
    "th08 Stats Clear Count": "Liczba przejść  %6d %6d %6d %6d %6d %6d",
    "th08 Stats Continue": "Kontynuacje  %6d %6d %6d %6d %6d %6d",
    "th08 Stats Practice": "Treningi  %6d %6d %6d %6d %6d %6d",
    "th08 Spell Practice Easy Mode": "Trening Zaklęć (Łatwy)",
    "th08 Spell Practice Normal Mode": "Trening Zaklęć (Normalny)",
    "th08 Spell Practice Hard Mode": "Trening Zaklęć (Trudny)",
    "th08 Spell Practice Lunatic Mode": "Trening Zaklęć (Szalony)",
    "th08 Spell Practice Extra Mode": "Trening Zaklęć (Extra)",
    "th08 Spell Practice Last Word": "Trening Zaklęć (Ostatnie Słowa)",
    "th08 Spell Practice List Description": "Zdobyto / Wyzwano (Sumy z gry głównej)",
    "th08 Spell Practice Highscore Title": "Zdobyto/Wyzwano[Wynik calkowity]　%s　Wszystkie postacie",
    "th08 Spell Practice Comment": "Komentarz karty",
    "th08 Spell Practice Last Spell": "Ostatnie",
    "th08 Spell Condition Line 1 205": "Ukończ poziom Extra z co najmniej 7 zdobytymi",
    "th08 Spell Condition Line 2 205": "kartami Zaklęć, wliczając te, co ma Keine.",
    "th08 Spell Condition Line 1 206": "Ukończ Finał B co najmniej dwoma postaciami",
    "th08 Spell Condition Line 2 206 207 209": "Tryb trudności nie ma znaczenia.",
    "th08 Spell Condition Line 1 207": "Ukończ Finał B co najmniej trzema postaciami.",
    "th08 Spell Condition Line 1 208": "Zdobądź 50 kart zaklęć w trybie treningu Kart Zaklęć.",
    "th08 Spell Condition Line 2 208 211 217 220": "Liczy się suma postaci.",
    "th08 Spell Condition Line 1 209": "Ukończ Finał B co najmniej czterema postaciami.",
    "th08 Spell Condition Line 1 210": "Uzyskaj Kartę Zaklęć nr %.3d.",
    "th08 Spell Condition Line 1 211": "Zdobądź 15 Ostatnich Zaklęć w trybie Treningu Kart Zaklęć.",
    "th08 Spell Condition Line 1 212": "Uzyskaj Karty Zaklęć nr %.3d i %.3d",
    "th08 Spell Condition Line 2 212": "oraz zobacz Kartę Zaklęć nr %.3d chociaż raz.",
    "th08 Spell Condition Line 1 213": "Zobacz nr %.3d, %.3d oraz %.3d chociaż raz.",
    "th08 Spell Condition Line 2 213 214 222": "Nie trzeba ich zdobywać.",
    "th08 Spell Condition Line 1 214": "Zobacz nr %.3d, %.3d, %.3d oraz %.3d chociaż raz.",
    "th08 Spell Condition Line 1 215": "Zdobądź wszystkie karty zaklęć na Normalnym trybie",
    "th08 Spell Condition Line 2 215": "trudności za pomocą Marisy w trybie solo.",
    "th08 Spell Condition Line 1 216": "Pokonaj grę na co najmniej Trudnym trybie trudności Reimu",
    "th08 Spell Condition Line 2 216": "w trybie solo. Musi to być Finał B.",
    "th08 Spell Condition Line 1 217": "Zdobądź 120 kart zaklęć w trybie treningu Kart Zaklęć.",
    "th08 Spell Condition Line 1 218": "Ukończ Finał B co najmniej sześcioma postaciami.",
    "th08 Spell Condition Line 1 219": "Ukończ Extra co najmniej trzema postaciami.",
    "th08 Spell Condition Line 1 220": "Zdobądź 30 Ostatnich Zaklęć w trybie Treningu Kart Zaklęć.",
    "th08 Spell Condition Line 1 221": "Przejdź grę na Szalonym.",
    "th08 Spell Condition Line 2 221": "Postać i kontynuowanie nie mają znaczenia.",
    "th08 Spell Condition Line 1 222": "Zobacz każde inne Ostatnie Słowo chociaż raz.",
    "th08 fog": "Wyłącz mgłę (nierekomendowane)",
    "th08 depth test": "Wyłącz test głębi (nierekomendowane)",
    "th08 rasterizer mode": "Rozpocznij grę w trybie rasteryzatora referencyjnego (zakazane)",
    "th08 VSync": "Wyłącz synchronizację pionową (nierekomendowane)",
    "th08 color composition": "Wyłącz komponowanie kolorów tekstur (zakazane)",
    "alcostg": "Bar o Zmierzchu～Uwabami Breakers～",
    "th105": "Touhou Niebiosa Szkarłatnej Percepcji ~ Szkarłatna Rapsodia Pogody",
    "th12": "Touhou Statek Gwiezdnego Lotosu ~ Nieokreślony Obiekt Fantastyczny",
    "th123": "Touhou Niepercepcja Prawa Natury ~ Pościg za Tajemnicą Ogromnego Guignol",
    "th128": "Wielkie Wojny Wróżek ~ Touhou Trzy Wróżki",
    "th13": "Touhou Mauzoleum Boskich Dusz ~ Dziesięć Pragnień",
    "th135": "Touhou Elegancka Wieża Serca ~ Beznadziejna Maskarada",
    "th14": "Touhou Zamek Lśniących Igieł ~ Dwulicowa Osoba",
    "th143": "Amanojaku Danmaku  ~ Niemożliwe Karty Zaklęć",
    "th15": "Touhou Legenda Ultramarynowej Kuli ~ Dziedzictwo Księżycowego Królestwa",
    "th155": "Touhou Kwiaty Opętania ~ Antynomia Pospolitych Kwiatów",
    "th165": "Pamiętnik Koszmarów Sekretnego Pieczętowania ~ Fioletowy Detektor",
    "th17": "Touhou Bestia w Kształcie Oni ~ Chytra Bestia i Najsłabsza Kreatura",
    "th175": "Touhou Dziwna Opowieść Chciwości ~ Zatopione Piekło Rozpaczy",
    "th16": "Touhou Niebiański Jadeitowy Wóz ~ Ukryta Gwiazda w Porach Roku",
    "th18": "Touhou Tęczowa Jaskinia Smoka ~ Niepołączeni Handlarze",
    "megamari": "MegaMari - Ambicja Marisy",
    "nsml": "Marisa i 6 Grzybów - New Super Marisa Land",
    "th185": "Czarny Rynek Pociskofilów ~ Setny Czarny Rynek",
    "th125": "Podwójna Sensacja ~ Touhou Album Słów Kwiatów",
    "th145": "Touhou Zapis Głębokich Sekretów ~ Legendy Miejskie w Stanie Pośrednim",
    "th08 Spell Practice Owner/Difficulty Line": "Uzytkownik  %s　　%s %s",
    "th07 Full Power": "Pelna Moc!",
    "th09 Menu Story Start": "Rozpocznij tryb Podziwiania Kwiatów",
    "th09 Menu Extra Start": "Rozpocznij poziom Extra",
    "th09 Menu Match Start": "Rozpocznij rozgrywkę z innym graczem, komputerem, lub pomiędzy komputerami",
    "th09 Menu Replay": "Obejrzyj powtórki",
    "th09 Menu Result": "Zobacz statystyki",
    "th09 Menu Music Room": "Wejdź do kącika muzycznego",
    "th09 Option BGM": "Zmień tryb odtwarzania muzyki. *MIDI nie jest obecnie wspierane.",
    "th09 Key Side": "Wybierz Gracza 1 lub 2.",
    "th09 Key Control Type": "PAD 1 lub 2: używaj dżojpada; Pełne, Lewo lub Prawo: klawiatura",
    "th09 Key Charge Type": "Zmień zachowanie przycisku ładowania",
    "th09 Key Shot": "Ustaw klawisz strzału",
    "th09 Key Bomb": "Ustaw klawisz bomby",
    "th09 Key Slow": "Ustaw klawisz niskiej szybkości lub ładowania",
    "th09 Option Key Config": "Ustaw sterowanie",
    "th06_ascii_result_clear": "(U)",
    "th09 gamepad 1": "Gamepad 1",
    "th09 gamepad 2": "Gamepad 2",
    "th09 all keyboard": "Pełna klawiatura",
    "th09 left side keyboard": "Lewa strona",
    "th09 right side keyboard": "Prawa strona",
    "th09 no save": "Wyjdź bez zapisywania",
    "th09 save": "Wyjdź i zapisz",
    "th09 1P controller": "Sterowania gracza 1",
    "th09 2P controller": "Sterowanie gracza 2",
    "th09 full rate": "0 (domyślne)",
    "th10 always ask": "Zawsze pytaj",
    "th10 slowshot": "Przycisk strzału jako przycisk zwolnienia",
    "th10 faith meter": "Pokaż pasek wiary przy postaci",
    "th10 screen mode": "Tryb uruchomienia gry",
    "th18_ascii_menu_music_room": "Kacik muzyczny",
    "th18_ascii_menu_option": "Opcja",
    "th18_ascii_menu_game_start": "Zacznij gre",
    "th06_ascii_reimu_a": "ReimuA",
    "th06_ascii_reimu_b": "ReimuB",
    "th06_ascii_marisa_a": "MarisaA",
    "th06_ascii_marisa_b": "MarisaB",
    "th06_ascii_extra": "Extra",
    "th095_scene_photo_count": "Zdj.  %.2d/%.2d",
    "th095_scene_score": "  Wynik %.7d",
    "th095_scene_hiscore": " Rekord %.7d",
    "th095_bestshot_overwrite": "Nadpisano Najl. Zdjecie!",
    "th095_results_slow_rate": "Spowolnienie   %2.0f%%",
    "th095_results_total_score": "       Suma  %.8d",
    "th095_results_high_score": "     Rekord  %.7d",
    "th095_results_score": "      Wynik  %.7d",
    "th095_results_shot": "    Zdjecie   %.6d",
    "th095_results_best_shot": "Najlepsze Zdjecie  %.6d",
    "th095_menu_slow_rate": "Spowoln.   %2.0f%%",
    "th095_menu_high score": "Rekord     %.6d",
    "th095_menu_scene_success_amount": "Pokonano Scen:%2d",
    "th09 Stage Format": "POZIOM %d %.2d:%.2d",
    "th095_ascii_replay_save": "Nr %.2d %s %s-%s %.2d/%.2d %.2d:%.2d %6d",
    "th095_ascii_replay_save_empty": "Nr %.2d %s %s-%s %s ------",
    "th095_ascii_replay": "Nr %.2d %s %s-%s %.2d/%.2d/%.2d %.2d:%.2d %6d %2.0f%%",
    "th095_ascii_replay_empty": "Nr %.2d --------  *-* --/--/-- --:-- ------ --%%",
    "th09 Replay": "Nr %.2d %.8s %8s",
    "th09 5th": "5ty",
    "th09 4th": "4ty",
    "th09 3rd": "3ci",
    "th09 2nd": "2gi",
    "th09 1st": "1szy",
    "th09 Extra Ranking": "Ranking - Extra",
    "th09 Lunatic Ranking": "Ranking - Szalony",
    "th09 Hard Ranking": "Ranking - Trudny",
    "th09 Normal Ranking": "Ranking - Normalny",
    "th09 Easy Ranking": "Ranking - Latwy",
    "th09 No Name": "Anonim ",
    "th09 Extra Mode": "Tryb Extra",
    "th09 Vs Format": "%.8s kontra %.8s",
    "th09 Normal": "Normalny",
    "th09 Easy": "Latwy  ",
    "th09 Hard": "Trudny ",
    "th09 Lunatic": "Szalony",
    "th09 Story Mode": "Tryb Opowiesci",
    "th09 Human vs Com": "Gracz kontra Komputer",
    "th09 Com vs Human": "Komputer kontra Gracz",
    "th09 Com vs Com": "Komputer kontra Komputer",
    "th09 Human vs Human": "Gracz kontra Gracz",
    "th095_ascii_user_replay": "Gracz%.4s %s %s-%s %.2d/%.2d/%.2d %.2d:%.2d %6d %2.0f%%",
    "th095_ascii_user_replay_empty": "Gracz---- --------  *-* --/--/-- --:-- ------ --.-%%",
    "th095_select_replay_number": "Wybierz Nr Powtorki",
    "th095_replay_name_regist": "Spis Nazwy Powtorki",
    "th07 Practice Stage Header": "Poziom   Rekord",
    "th07 Replay Stage Header": "Poziom   Koncowy Wynik",
    "th07 Replay Header": "Nr    Nazwa      Data  Postac   Tryb",
    "th07 Replay Save Empty": "Nr %.2d -------- --/--  -------          0",
    "th07 Replay Save": "Nr %.2d %8s %5s  %7s %9d0",
    "th07 Date Format": "%d/%m",
    "th07 Replay Save Header": "Nr    Nazwa    Data   Postac Wynik",
    "th07 Results Header": "Nr  Nazwa     Wynik(Poziom) Data   Spowoln.",
    "th07 Max Bonus": "MaksBonus %8d",
    "th06_practice_format": "POZIOM %d  %.10d",
    "th08 Last Spell Failed": "Nie Pokonano Ostatniego Zaklecia",
    "th08 Results Header": "Nr  Nazwa      Wynik(Poziom)  Data   Spowoln.",
    "th08 Now Playing": "Teraz Gra",
    "th08 Spell Practice Total": "%sW sumie",
    "th08 Spell Practice Card No": "%sNr %.3d",
    "th08 Spell Replay": "%s %8s  %6s %7s  Karta Nr %3d",
    "th08 Replay Spell Number": "Nr %.3d %9d0",
    "th06_error_two_instances": "Nie można uruchomić drugiej instancji.\n",
    "th06_log_tl_hal": "Używane są T&L oraz warstwa abstrakcji sprzętowej.\n",
    "th06_log_directsound_init": "Pomyślnie zainicjowano DirectSound.\n",
    "th06_log_no_gamepad": "Niestety nie znaleziono gamepada.\n",
    "th06_log_unable_to_read_file": "Nie można odczytać %s.\n",
    "th06_log_directinput_init": "Pomyślnie zainicjowano DirectInput.\n",
    "th06_log_sound_file_read_error": "Błąd: Nie można wczytać pliku dźwiękowego. Sprawdź dane %s.\n",
    "th06_log_sprite_read_error": "Nie można wczytać animacji sprite'a %s. Dane są uszkodzone lub niedostępne.\n",
    "th06_log_header": "Rejestr Touhou --------------------------------------------- \n",
    "th06_log_valid_pad": "Znaleziono działającego pada.\n",
    "th06_log_texture_read_error": "Nie można wczytać tekstury %s. Dane są uszkodzone lub niedostępne.\n",
    "th06_log_export_failure": "Nie można nadpisać pliku %s\n",
    "th06_log_read_only_full_disk": "Czy folder ma ustawiony atrybut tylko do odczytu lub może dysk jest zapełniony?\n",
    "th06_log_reinit_corrupt_config": "Dane konfiguracyjne były uszkodzone, więc zostały ponownie zainicjowane.\n",
    "th06_log_reinit_missing_config": "Dane konfiguracyjne były niedostępne, więc zostały ponownie zainicjowane.\n",
    "th06_log_character_init_failure": "Błąd: Nie udało się zainicjować znaków.\n",
    "th06_log_tl_hal_unavailable": "T&L oraz warstwa abstrakcji sprzętowej nie wydają się być dostępne.\n",
    "th06_log_hal_unavailable": "Warstwa abstrakcji sprzętowej też nie wydaje się być dostępna.\n",
    "th06_log_first_startup_16bit": "Pierwsze uruchomienie, ekran zainicjowano w 16 bitach.\n",
    "th06_log_first_startup_32bit": "Pierwsze uruchomienie, ekran zainicjowano w 32 bitach.\n",
    "th06_log_direct3d_init_failure": "Nie udało się zainicjować Direct3D, gra nie jest w stanie działać.\n",
    "th06 config export failure": "Nie udało się nadpisać pliku.\nCzy posiada on atrybut tylko do odczytu?",
    "th09 config export failure": "Nie udało się nadpisać pliku.\nSprawdź, czy nie posiada on atrybutu tylko do odczytu.",
    "th06_log_vertex": "Vertex buffer jest wyłączony.\n",
    "th06_log_fog": "Mgła jest wyłączona.\n",
    "th06_log_16bit_textures": "Wymuszane są 16-bitowe tekstury.\n",
    "th06_log_Gouraud_shading": "Cieniowanie Gourauda jest ograniczane.\n",
    "th06_log_color_composition": "Komponowanie kolorów tekstur jest wyłączone.\n",
    "th06_log_rasterizer_mode": "Wymuszany jest tryb rasteryzatora referencyjnego.\n",
    "th06_log_clear_buffer": "Wymuszone jest czyszczenie backbuffera.\n",
    "th06_log_backbuffer_nonlocking_suggestion": "Próba odblokowania backbuffera.\n",
    "th06_log_minimum_graphics": "Rendering przedmiotów w grze jest ograniczany.\n",
    "th06_log_depth_test": "Test głębi jest wyłączony.\n",
    "th06_log_force_frame": "Wymuszane jest 60 klatek na sekundę.\n",
    "th06_log_directinput_usage": "DirectInput nie jest używany do pada ani klawiatury.\n",
    "th06_log_window_mode": "Gra jest uruchamiana w trybie okienkowym.\n",
    "th07_log_reinit_abnormal_config": "Dane konfiguracyjne były dziwne, więc zostały ponownie zainicjowane.\n",
    "th07_log_async_vsync_test": "Sprawdzanie, czy asynchroniczny Vsync jest możliwy.\n",
    "th07_log_async_update_failure": "Asynchroniczne aktualizacje też nie są możliwe. Zmiana na najmniej czysty tryb.\n",
    "th07_log_refresh_rate_suggestion": "*** Sugerowana jest zmiana częstotliwości odświeżania na 60Hz ***\n",
    "th07_log_BGM_memory": "Muzyka jest wczytywana do pamięci.\n",
    "th07_log_draw_screen": "HUD jest przerysowywany co klatkę.\n",
    "th07_log_Vsync": "Synchronizacja pionowa jest wyłączona.\n",
    "th095_log_refresh_rate_suggestion": "Spróbuj zmienić częstotliwość odświeżania na 60Hz.",
    "th06_log_refresh_rate": "Częstotliwość odświeżania zmieniona na 60Hz.\n",
    "th11 input latency": "Czas oczekiwania wejścia",
    "th11 stable input": "Stabilny (jeśli wejście nie działa często)",
    "th11 normal input": "Zwykły (małe użycie procesora)",
    "th11 automatic input": "Automatyczny (wykryj najszybszą odpowiedź) *Domyślny",
    "th11 fast input": "Szybki (jeśli automatyczny nie działa poprawnie)",
    "th11 input description": "Wybierz rodzaj czas oczekiwania dla odpowiedniej odpowiedzi wejścia.\nStabilny i zwykły odpowiadają na wejście z poprzedniej klatki.\nAutomatyczny próbuje dostarczyć najszybszą możliwą odpowiedź.\nSzybki zapewnia podobne efekty co automatyczny, ale obraz może być zniekształcony.\n*Działa tylko gdy pomijanie klatek jest wyłączone*",
    "th105_replay_return_to_title": "Wychodzisz do ekranu tytułowego. Zapisać powtórkę?",
    "th105_replay_return_to_select": "Wychodzisz do ekranu wyboru. Zapisać powtórkę?",
    "th105_replay_saved": "Zapisano powtórkę.",
    "th105_replay_save": "Zapisać powtórkę?",
    "th105_replay_delete": "Usunąć powtórkę?",
    "th105_continue": "Kontynuować? Pozostałe próby: %d",
    "th105_init_failed": "Nie udało się zainicjalizować",
    "th105_netplay_select_addr": "Proszę wybrać połączenie",
    "th105_netplay_port": "Proszę wpisać numer portu, który ma zostać użyty...",
    "th105_netplay_enter_addr": "Proszę wpisać adres docelowego połączenia",
    "th105_netplay_allow_spectating": "Zezwolić na udział widzów?",
    "th105_netplay_await": "Czekam na połączenie...",
    "th105_netplay_no_spectating": "Wyłączono widzów",
    "th105_netplay_game_not_available": "Gra jeszcze się nie rozpoczęła",
    "th105_netplay_connection_failed": "Błąd połączenia.",
    "th105_netplay_connecting": "Nawiązywanie połączenia...",
    "th105_netplay_confirm_address": " jest poprawnym adresem?",
    "th105_netplay_already_playing": "Już w trakcie gry.",
    "th105_netplay_already_playing_spectate": "Gra już jest rozpoczęta. Czy chcesz dołączyć jako widz?",
    "th105_delete_failed": "Błąd usunięcia.",
    "th105_delete_suceeded": "Usunięto.",
    "th105_profile_save_changes": "Zakończ tworzenie. Zapisać zmiany?",
    "th105_profile_deck_too_big": "W talii musi być 20 kart.",
    "th105_profile_creation_failed": "  - błąd tworzenia.",
    "th105_profile_created": "  - stworzono pomyślnie.",
    "th105_profile_copied": "Skopiowano profil.",
    "th105_profile_copy_failed": "Błąd kopiowania profilu.",
    "th105_profil_rename_failed": "Błąd zmiany nazwy.",
    "th105_profil_renamed": "Zmieniono nazwę.",
    "th105_profile_overwrite": "  - czy na pewno nadpisać?",
    "th105_profile_will_copy": "  - czy na pewno skopiować?",
    "th105_profile_will_delete": "  - czy na pewno usunąć?",
    "th123_replay_create_folder_failed": "Błąd stworzenia folderu powtórek.",
    "th123_profile_create_folder_failed": "Błąd stworzenia folderu profili.",
    "th105_netplay_connect_for_match": "Czy chcesz grać?"
}