{
    "th09_01": "Kurhan Odzwierciedlający Kwiaty ~ Do Higan i z Powrotem",
    "th09_02": "Wiosenny Pas ~ Kolorowa Ścieżka",
    "th09_03": "Orientalny Ciemny Lot",
    "th09_04": "Kwitnąca Noc",
    "th09_05": "Upiorny Wschodni Sen ~ Starożytna Świątynia",
    "th09_06": "Szalone Oczy ~ Niewidzialna Pełnia Księżyca",
    "th09_07": "Przygody Zakochanej Chłopczycy",
    "th09_08": "Nawiedzony Zespół ~ Upiorna Kapela",
    "th09_09": "Głuchota na Wszystko Prócz Pieśni ~ Kwiecisty Mix",
    "th09_10": "Biała Flaga Czcigodnego Pana Usy",
    "th09_11": "Młoda Bogini Wiatru",
    "th09_12": "Trujące Ciało ~ Porzucona Lalka",
    "th09_13": "Przeszłość i Teraźniejszość Gensokyo ~ Kraina Kwiatów",
    "th09_14": "Do Higan i z Powrotem ~ Nadrzeczny Krajobraz",
    "th09_15": "Wschodni Sąd Sześćdziesiątego Roku ~ Los Sześćdziesięciu Lat",
    "th09_16": "Kurhan Gdzie Odzwierciedlają Kwiaty",
    "th09_17": "Kurhan Shigan",
    "th09_18": "Kwiaty Pozostałe W Fantazji",
    "th09_19": "Kwiat Duszy ~ Kolejny Sen...",
    "th10_01": "Zapieczętowani Bogowie",
    "th10_02": "Bóg Tęskniący za Ludźmi ~ Romantyczna Jesień",
    "th10_03": "Bo Księżniczka Inada Mnie Beszta",
    "th10_04": "Droga Boga Nieszczęść ~ Mroczna Droga",
    "th10_05": "Mroczna Strona Przeznaczenia",
    "th10_06": "Gensokyo Uwielbiane przez Bogów",
    "th10_07": "„Kappa” Ryūnosuke Akutagawy ~ Szczera Przyjaciółka",
    "th10_08": "Spad Jesieni ~ Jesienny Wodospad",
    "th10_09": "Góra Youkai ~ Tajemnicza Góra",
    "th10_10": "Starożytny Krajobraz Japonii Widziany przez Dziewczynkę",
    "th10_11": "Wiara Jest dla Przemijających Ludzi",
    "th10_12": "Cmentarz Onbashiry ~ Grób Istnienia",
    "th10_13": "Sędziwe Starożytne Pole Bitwy ~ Pole Wojenne w Suwie",
    "th10_14": "Jutro Będzie Wyjątkowe, Wczoraj Nie Było",
    "th10_15": "Rdzenna Wiara",
    "th10_16": "Chram u Podnoża Góry",
    "th10_17": "Bogowie Zsyłają Nam Upragniony Deszcz ~ Sylfidowy Sen",
    "th10_18": "Wyniki Gracza",
    "th11_01": "Przebudzenie Dusz Ziemi",
    "th11_02": "Mroczny Otwór Wentylacyjny",
    "th11_03": "Zapieczętowany Youkai ~ Utracone Miejsce",
    "th11_04": "Most, Którego Ludzie Już Nie Przekraczają",
    "th11_05": "Zielonooka Zazdrość",
    "th11_06": "Wędrówka po Ulicach Dawnego Piekła",
    "th11_07": "Wysadzane Kwiatami Naczynie Do Sake Góry Ooe",
    "th11_08": "Zachcianka z Głębi Serca",
    "th11_09": "Panna Satori ~ Trzecie Oko",
    "th11_10": "Kołysanka Opuszczonego Piekła",
    "th11_11": "Podróż Truposzy ~ Raduj się!",
    "th11_12": "Płaszcz Piekielnego Ognia",
    "th11_13": "Słoneczna Sekta Mistycznej Wiedzy ~ Synteza Jądrowa",
    "th11_14": "Ostatnia Odległość",
    "th11_15": "Youkai Dziewczynka Hartmanna",
    "th11_16": "Powrót Ziemskich Dusz Do Domu",
    "th11_17": "Świt Energii ~ Sen Przyszłości...",
    "th128_01": "Lodowa Wróżka Wiosną",
    "th128_02": "Przyśpiew Przepięknej Wielkiej Wojny",
    "th128_03": "Ryzykując Swym Życiem Dla Żartu",
    "th128_04": "Ciekawość Pochłonięta z Całego Roku",
    "th128_05": "Taniec Wróżek o Północy",
    "th128_06": "Wielkie Wojny Wróżek ~ Wojny Wróżek",
    "th128_07": "Lekki Deszcz",
    "th128_08": "Noc Magów",
    "th128_09": "Lodowa Wróżka Wiosną - Spokój -",
    "th128_10": "Wyniki Gracza",
    "th13_01": "Duch Chciwości",
    "th13_02": "Nocna Sakura Zmarłych Dusz",
    "th13_03": "Trop Widma",
    "th13_04": "Witamy w Świątyni Youkai",
    "th13_05": "Youkai Dziewczynka przy Bramie",
    "th13_06": "Zamieszkajmy na Uroczym Cmentarzu",
    "th13_07": "Sztywny Raj",
    "th13_08": "Popęd Pragnień",
    "th13_09": "Stary Odległy Pustelnik",
    "th13_10": "Wielkie Mauzoleum w Sali Snów",
    "th13_11": "Legenda Wielkich Bogów",
    "th13_12": "Gwiaździste Niebo Małych Pragnień",
    "th13_13": "Legenda Shoutoku ~ Prawdziwy Administrator",
    "th13_14": "Droga Youkai za Świątynią",
    "th13_15": "Futatsuiwa z Sado",
    "th13_16": "Nowy Wiatr w Świątyni",
    "th13_17": "Sen Pragnienia",
    "th14_01": "Tajemnicza Różdżka do Egzorcyzmów",
    "th14_02": "Jezioro Mgły",
    "th14_03": "Syrena z Nieznanej Krainy",
    "th14_04": "Ludzie i Youkai Przemierzający Kanał",
    "th14_05": "Dullahan pod Wierzbami",
    "th14_06": "Bambusowy Las Pełni Księżyca",
    "th14_07": "Samotny Wilkołak",
    "th14_08": "Magiczna Burza",
    "th14_09": "Iluzoryczne Joururi",
    "th14_10": "Zamek Błyszczącej Igły Tonący w Powietrzu",
    "th14_11": "Odwrotna Ideologia",
    "th14_12": "Przesadzona wieża",
    "th14_13": "Kobito Lśniącej Igły ~ Mała Księżniczka",
    "th14_14": "Chmury Burzowe Magicznej Mocy",
    "th14_15": "Pierwotny Rytm ~ Nieskazitelny Rytm",
    "th14_17": "Dziwne, Dziwne Instrumenty",
    "th12_01": "Cień na Błękitnym Niebie",
    "th12_02": "W Przystani Wiosny",
    "th12_03": "Mały, Tyci Sprytny Dowódca",
    "th12_04": "Szlak Zapieczętowanych Chmur",
    "th12_05": "Uważajcie na Parasolkę Pozostawioną Tu na Wieki",
    "th12_06": "Niebiańskie Ruiny",
    "th12_07": "Tradycyjny Staruszek i Stylowa Dziewczyna",
    "th12_08": "Międzywymiarowa Podróż Pasażerskiego Statku Widmo",
    "th12_09": "Kapitan Murasa",
    "th12_10": "Ezoteryka Sielskiego Miasta Makai",
    "th12_11": "Bishamonten o Tygrysim Motywie",
    "th12_12": "Płomienie Hokkai",
    "th12_13": "Czuły Podniebny Żagiel ~ Kosmiczny Umysł",
    "th12_14": "Romans z UFO na Nocnym Niebie",
    "th12_15": "Obcy Okresu Heian",
    "th12_16": "Świątynia Youkai",
    "th12_17": "Powrót z Niebios do Domu ~ Niebiański Sen",
    "th15_01": "Pojawienie się Kosmicznej Kapłanki",
    "th15_02": "Niezapomniana Nostalgiczna Zieleń",
    "th15_03": "Królik Wylądował",
    "th15_04": "Jezioro Odbijające Oczyszczone Światło Księżyca",
    "th15_05": "Wrześniowa Dynia",
    "th15_06": "Tajemnicza Kapłanka Lecąca przez Kosmos",
    "th15_07": "Wieczny Wiosenny Sen",
    "th15_08": "Zamrożona Wieczna Stolica",
    "th15_09": "Odwrócone Koło Fortuny",
    "th15_10": "Odległa Podróż 380,000 Kilometrów",
    "th15_11": "Błazen Flagi Rozświetlonej Gwiazdami",
    "th15_12": "Morze, w Którym Widać Odbicie Ojczystej Planety",
    "th15_13": "Czyste Furie ~ Miejsce Pobytu Serca",
    "th15_14": "Świat Koszmarów Nigdy Wcześniej Nie Widzianych",
    "th15_15": "Planeta Pandemonium",
    "th15_16": "Księżyc Widziany ze Świątyni",
    "th15_17": "Kosmiczna Kapłanka Wraca do Domu",
    "th06_01": "Sen Bardziej Szkarłatny niż Czerwony",
    "th06_02": "Dusza tak Szkarłatna, jak Owoce Miechunki",
    "th06_03": "Zjawy Grasujące Nocą",
    "th06_04": "Półksiężycowy Elf",
    "th06_05": "Zakochana Chłopczyca",
    "th06_06": "Szkarłatna Szanghajska Herbaciarnia ~ Chińska Herbata",
    "th06_07": "Alicja z Szanghaju roku Meiji 17",
    "th06_08": "Voile, Magiczna Biblioteka",
    "th06_09": "Zamknięta Dziewczyna ~ Zamknięty Pokój Dziewczyny",
    "th06_10": "Pokojówka i Kieszonkowy Zegarek Krwi",
    "th06_11": "Zegar Księżycowy ~ Cyferblat Księżyca",
    "th06_12": "Młoda Potomkini Țepeșa",
    "th06_13": "Septet dla Martwej Księżniczki",
    "th06_14": "Cowieczna Uroczystość Magicznych Dziewcząt",
    "th06_15": "U.N. Owen to Ona?",
    "th06_16": "Wieczność Bardziej Ulotna niż Szkarłat",
    "th06_17": "Szkarłatna Wieża ~ Wschodni Sen...",
    "th143_01": "Wznieś Flagę Oszustwa",
    "th143_02": "Oszukiwanie Niemożliwego Danmaku",
    "th143_03": "Karta Zaklęć o Północy",
    "th143_04": "Romantyczna Ucieczka Lotem",
    "th143_05": "Wieczno-Chwilowe Panowanie",
    "th143_06": "Syrena z Nieznanej Krainy",
    "th143_07": "Odwrotna Ideologia",
    "th143_08": "Iluzoryczne Joururi",
    "th143_09": "Góra Youkai ~ Tajemnicza Góra",
    "th105_01": "Niebiosa Szkarłatnej Percepcji",
    "th105_02": "Zwykłe Dni",
    "th105_03": "Kolor Ziemi to Żółty",
    "th105_04": "Argumentować Za i Przeciw",
    "th105_05": "Piękny Widok Natury",
    "th105_06": "Aromatyczne Drzewa, Kwiaty i Liście",
    "th105_07": "Tańczący Wodny Prysznic",
    "th105_08": "Machnij Rybą by Odgonić Muchy",
    "th105_09": "Wolne i Łatwe",
    "th105_10": "Niedorzeczna Gra",
    "th105_11": "Pijany tak, jak Lubię",
    "th105_12": "Błękitne Niebo za Chmurami",
    "th105_13": "Szkarłat w Czarnym Morzu ~ Legendarna Ryba",
    "th105_14": "Nieskazitelne Odzienie Niebiańskich",
    "th105_15": "Katastrofa w Bhavaagrze ~ Cudowny Raj",
    "th105_16": "Bhavaagra Widziana Umysłem Dziecka",
    "th105_17": "Ciemniejący Zmrok",
    "th105_18": "Wschodnie Niebiosa Szkarłatnej Percepcji",
    "th105_19": "Wschodnie Mistyczne Konsultacje Miłosne",
    "th105_20": "Pojemnik Gwiazd ~ Szkatułka Gwiazdy",
    "th105_21": "Kwitnąca Noc",
    "th105_22": "Lalkarz z Bukaresztu",
    "th105_23": "Hiroari Strzela do Tajemniczego Ptaka ~ Do Kiedy?",
    "th105_24": "Zamknięta Dziewczyna ~ Zamknięty Pokój Dziewczyny",
    "th105_25": "Kwitnij Szlachetnie, Tuszo-Czarny Kwiecie Wiśni ~ Granica Życia",
    "th105_26": "Septet dla Martwej Księżniczki",
    "th105_27": "Zapada Noc ~ Gwiazda Wieczorna",
    "th105_28": "Złamany Księżyc",
    "th105_29": "Szalone Oczy ~ Niewidzialna Pełnia Księżyca",
    "th105_30": "Młoda Bogini Wiatru",
    "th105_31": "Do Higan i z Powrotem ~ Nadrzeczny Krajobraz",
    "th123_01": "Widziałeś Ten Cień?",
    "th123_02": "Gromadzone Marzenie",
    "th123_03": "Legendarny Tytan",
    "th123_04": "Wiara Jest dla Przemijających Ludzi",
    "th123_05": "Zakochana Chłopczyca",
    "th123_06": "Sceneria Pełna Lalek",
    "th123_07": "Szkarłatna Szanghajska Herbaciarnia ~ Chińska Herbata",
    "th123_08": "Słoneczna Sekta Mistycznej Wiedzy ~ Synteza Jądrowa",
    "th123_09": "Nasz Hisoutensoku",
    "th123_10": "Nieznane X ~ Nieodkryta Przygoda",
    "th123_11": "X: Latający Obiekt na Niebie",
    "th123_12": "Dwukolorowy Motyl Lotosu ~ Starożytni",
    "th123_13": "Magia w Kolorze Miłości",
    "th123_14": "Grymuar Alicji",
    "th123_15": "Voile, Magiczna Biblioteka",
    "th123_16": "Jutro Będzie Wyjątkowe, Wczoraj Nie Było",
    "th123_17": "Wieczna Maszyna Parowa",
    "th123_18": "Wielki Cień i Tyci Wniosek",
    "th123_19": "Wschodnie Mistyczne Konsultacje Miłosne (Wersja Przełomu Wieku)",
    "th075_01": "Gromadzone Marzenie",
    "sh01_18": "Dwukolorowy Motyl Lotosu ~ Starożytni",
    "th02_09": "Magia w Kolorze Miłości",
    "th05_17": "Grymuar Alicji",
    "th03_03": "Wschodnie Mistyczne Konsultacje Miłosne",
    "th04_11": "Pojemnik Gwiazd ~ Szkatułka Gwiazdy",
    "th07_06": "Lalkarz z Bukaresztu",
    "th07_11": "Hiroari Strzela do Tajemniczego Ptaka ~ Do Kiedy?",
    "th07_13": "Kwitnij Szlachetnie, Tuszo-Czarny Kwiecie Wiśni ~ Granica Życia",
    "th075_17": "Zapada Noc ~ Gwiazda Wieczorna",
    "th075_34": "Złamany Księżyc",
    "th08_12": "Szalone Oczy ~ Niewidzialna Pełnia Księżyca",
    "th_main": "Motyw Wschodniej Opowieści",
    "th04_18": "Uroczy Diabeł ~ Niewinność",
    "th075_05": "Bal Czarownic",
    "sh01_17": "Bal Czarownic ~ Mag",
    "mcd_02_04": "Starożytna Świątynia Zaświatów",
    "th08_03": "Drganie Jesiennego Księżyca ~ Księżycowy Owad",
    "mcd_fairy02_02": "Kraina Olśniewającej Piękności Natury",
    "alcostg_06": "Lemuria Pijaka",
    "alcostg_05": "Goniąc Zmierzch",
    "alcostg_03": "Festiw-al-koholików",
    "mcd_ssib_03": "Lemuria Pijaka (wersja retro)",
    "mcd_fairy05_01": "Zabawa w Chowanego w Świątyni",
    "th135_11": "Futatsuiwa z Gensokyo",
    "th135_12": "Utracona Emocja",
    "th135_13": "Niezmienny Pesymizm Tego Nędznego Świata",
    "th135_14": "Orkiestra Shinkirou",
    "th135_15": "Poranne Chmury",
    "th135_22": "Wieś w Środku Nocy",
    "th145_16": "Ostateczny Okultyzm ~ Ezoteryczka Współczesnego Świata",
    "th145_14": "Kwieciste Pole Bitwy",
    "th16_13": "Ukryte Cztery Pory Roku",
    "th16_15": "Tajemna Bogini Matara ~ Ukryta Gwiazda Wszystkich Pór Roku",
    "th16_14": "Koniec z Przechodzeniem przez Drzwi",
    "th155_36": "Yorimashi Między Snem a Rzeczywistością ~ Nekrofantazja",
    "th155_37": "Gwiazdą Wieczoru jest Swobodna Egoistka ~ Kwiaty Egoizmu",
    "th155_35": "Bhavaagra jak Okiem Sięgnąć",
    "th155_34": "Parada Śniących Owiec",
    "th165_01": "Pamiętnik Koszmarów",
    "th165_04": "Koszmarny Pamiętnik",
    "th155_50": "Nieskazitelne Odzienie Niebiańskich ~ Żółta Lilia",
    "th155_31": "Przezwyciężyć Tysiąc Prób",
    "th155_19": "Kolor Ziemi jest Żółty ~ Pierwiosnek",
    "th155_20": "Grzybowy Walc",
    "th155_22": "Równość pod Prawem Dharmy",
    "th155_26": "Róża Kwitnąca w Podziemiu",
    "th155_29": "Nieśmiertelna Czerwona Dusza",
    "touki_01": "BOŻY SĄD",
    "th16_16": "Nienaturalna Natura",
    "th165_02": "Świadomy Marzyciel",
    "th165_03": "Szalony Marzyciel",
    "mcd_ssib_02": "Karta Zaklęć Watatsuki ~ Szalony Błękit",
    "mcd_fairy02_03": "Gwiezdny Wojaż 2008",
    "th04_01": "Gensokyo ~ Opowieść Krainy Lotosu",
    "zsw_06": "Iluzja Hourai ~ Daleki Wschód",
    "mcd_pmiss_03": "Nocny Lot nad Hatoyamą - mocny MIX",
    "th14_16": "Magiczna Moc Młotka",
    "mcd_07_02": "Prowadzeni przez Krowę do Świątyni Zenkou",
    "mcd_07_01": "Zielone Sanatorium",
    "mcd_06_10": "Gensokyo Zawieszone w Przestrzeni Kosmicznej",
    "th14_18": "Wyniki Gracza",
    "th135_02": "Wiosenny Pas ~ Kolorowa Ścieżka",
    "th135_03": "Noc Magów",
    "th135_04": "Tradycyjny Staruszek i Stylowa Dziewczyna",
    "th135_05": "Czuły Podniebny Żagiel ~ Kosmiczny Umysł",
    "th135_06": "Legenda Wielkich Bogów",
    "th135_07": "Legenda Shoutoku ~ Prawdziwy Administrator",
    "th135_08": "„Kappa” Ryūnosuke Akutagawy ~ Szczera Przyjaciółka",
    "th135_09": "Youkai Dziewczynka Hartmanna",
    "th135_10": "Futatsuiwa z Sado",
    "th135_16": "Oficjalna Gazeta Zmierzchu",
    "th135_19": "Popularne Miejsce",
    "th135_20": "Niepopularne Miejsce",
    "th145_01": "Poruszające Miejskie Legendy",
    "th145_02": "Odkrywanie Tajemnic Gensokyo",
    "th145_04": "Okultyzm à la Carte",
    "th145_05": "Przejaw Folkloru",
    "th145_13": "Ci Znający Prawdę",
    "th145_12": "Bambusowy Las w Ogniu",
    "th145_15": "Folklor Świata Zewnętrznego",
    "th145_17": "Każde Zakończenie",
    "th145_18": "Odkryte Arkana",
    "th145_19": "Dwukolorowy Motyl Lotosu ~ Czerwień i Biel",
    "th145_20": "Mistrzowska Iskra w Kolorze Miłości",
    "th145_21": "Tradycyjny Staruszek i Stylowa Dziewczyna",
    "th145_22": "Czuły Podniebny Żagiel ~ Kosmiczny Umysł",
    "th145_23": "Legenda Wielkich Bogów",
    "th145_24": "Legenda Shoutoku ~ Prawdziwy Administrator",
    "th145_25": "„Kappa” Ryūnosuke Akutagawy ~ Szczera Przyjaciółka",
    "th145_26": "Youkai Dziewczynka Hartmanna",
    "th145_27": "Futatsuiwa z Gensokyo",
    "th145_28": "Utracona Emocja",
    "th145_29": "Sięgaj po Księżyc, Nieśmiertelny Dymie",
    "th145_30": "Kobito Lśniącej Igły ~ Mała Księżniczka",
    "th15_18": "Wyniki Gracza",
    "mcd_08_01": "Historia Naturalna Dziecinnego Duetu",
    "mcd_08_02": "Zamrożona Wieczna Stolica",
    "mcd_08_03": "Zmęczone Oczy Doktora Latency",
    "mcd_08_04": "Wrześniowa Dynia",
    "th08_18": "Sięgaj po Księżyc, Nieśmiertelny Dymie",
    "mcd_08_07": "Zamek Błyszczącej Igły Tonący w Powietrzu",
    "mcd_08_09": "Morze, w Którym Widać Odbicie Ojczystej Planety",
    "mcd_08_10": "Czyste Furie ~ Miejsce Pobytu Serca",
    "scow_02_03": "Ostateczny Okultyzm ~ Ezoteryczka Współczesnego Świata",
    "mcd_09_03": "Odwrotna Ideologia",
    "mcd_09_05": "Legenda Wielkich Bogów",
    "mcd_09_06": "Planeta Pandemonium",
    "mcd_09_08": "Ezoteryka Sielskiego Miasta Makai",
    "th145_ps4_01": "Szalone Oczy ~ Niewidzialna Pełnia Księżyca",
    "th145_ps4_06": "Nieznane X ~ Okultystyczne Szaleństwo",
    "th145_ps4_07": "Wariactwo Szalonego Oblicza ~ Okropna Noc",
    "mcd_01_01": "Legenda Hourai",
    "th08_17": "Przedłużenie Popiołu ~ Człowiek Hourai",
    "th07_15": "Niepohamowane Dusze",
    "th07_17": "Niepohamowane Dusze ~ Kto to Zrobił!",
    "th08_21": "Piękno Wschodnich Youkai",
    "th125_03": "Nowoczesna Kolonia Youkai",
    "th155_41": "Nieznane X ~ Okultystyczne Szaleństwo",
    "th02_08": "Himorogi, Płoń w Fiolecie",
    "th01_11": "Od Teraz, do Chwili Twojej Śmierci",
    "th02_01": "Wschodnie, Udokumentowane Zapieczętowanie Demona ~ Kraina Czystej Mandali",
    "th02_07": "Zakład o Śmierć",
    "th02_10": "Wschodnie, Udokumentowane Zapieczętowanie Demona ~ Dziki Taniec Widma",
    "th03_02": "Wybór",
    "th03_06": "Tabula Rasa ~ Pusta Dziewczynka",
    "th03_19": "Klonowy Sen...",
    "th04_22": "Ci Żyjący w Złudzeniach",
    "zsw_07": "Nocny Lot nad Hatoyamą",
    "sh01_19": "One Same",
    "mcd_01_02": "Dwukolorowy Motyl Lotosu ~ Czerwień i Biel",
    "th07_07": "Sąd Lalek ~ Dziewczynka, Która Bawiła się Formami Ludzi",
    "th07_19": "Sen o Wiosennym Wietrzyku",
    "mcd_02_01": "Umieranie w Nocy na Polach Dendery",
    "mcd_02_02": "Dziewczęcy Klub Pieczętowania",
    "th08_08": "Zemsta za Wieczną Noc ~ Nieprzemijająca Noc",
    "th08_10": "Mistrzowska Iskra w Kolorze Miłości",
    "mcd_03_09": "Granica Między Snem a Rzeczywistością",
    "th08_05": "Głuchota Na Wszystko Prócz Pieśni",
    "mcd_04_01": "Hiroshige Nr 36 ~ Neo Super-Express",
    "mcd_04_05": "Legenda Aokigahary",
    "mcd_fairy01_02": "Nie Zasnę z Powodu Nocy",
    "mcd_pmiss_02": "Dziecię Rodu Are",
    "mcd_fairy02_01": "Incydent Sunny Milk ze Szkarłatną Mgłą",
    "thmj_01": "Ciekawa Stara Szanghajska Płytka",
    "mcd_fairy04_01": "Przygody Wróżek",
    "mcd_fairy04_02": "Dwa Światy",
    "mcd_055_01": "Nieznany Kwiat, Fascynująca Podróż",
    "mcd_06_08": "Bariera Świątyni Ame-no-Torifune",
    "mcd_07_09": "Zbierając Tajemnice z Całej Japonii",
    "th135_17": "Dzisiejszy Nagłówek na Pierwszej Stronie",
    "th135_23": "Wybór Wykonawcy",
    "th145_03": "Codzienne Życie z Kulami",
    "th145_11": "Wierz w Możliwości",
    "th145_10": "Dzwon Antypodów",
    "th145_09": "Nieznana Wartość",
    "mcd_08_05": "Chwila Krótsza niż Czas Plancka",
    "mcd_08_06": "Bakeneko Schrödingera",
    "mcd_08_08": "Błoniasta Ściana Tabu",
    "mcd_08_11": "Wieczno-Chwilowe Panowanie",
    "mcd_09_01": "Bar \"Old Adam\"",
    "mcd_09_02": "Ciemność Spowodowana przez Historię Naturalną",
    "mcd_09_07": "Karczma Ryzykantów ze Starego Świata",
    "th145_ps4_02": "Neo Bambusowy Las w Ogniu",
    "th145_ps4_03": "Dzwon Eonów",
    "th145_ps4_04": "Przyciąganie Okultystycznego",
    "th145_ps4_05": "Folklor Granicy",
    "th16_01": "Niebo, z Którego Opadają Kwiaty Wiśni",
    "th16_02": "Gwiazda Nadziei Pojawia się na Niebieskim Niebie",
    "th16_03": "Sen Wróżki Letniej",
    "th16_04": "Bezbarwny Wiatr na Górze Youkai",
    "th16_05": "Spotkanie w Głębi Gór",
    "th16_06": "Płyń w Morzu Koloru Kwiatów Wiśni",
    "th16_07": "Para Boskich Bestii",
    "th16_08": "Iluzoryczny Biały Podróżnik",
    "th16_09": "Magiczny Jizo ze Słomianym Kapeluszem",
    "th16_10": "Czy Zakazane Drzwi Prowadzą do Tego Świata, Czy Następnego?",
    "th16_11": "Szalone Tancerki Drugiego Planu",
    "th16_12": "Tylne Drzwi",
    "th16_17": "Biały Podróżnik",
    "th16_18": "Wyniki Gracza",
    "th155_01": "Dwukolorowy Motyl Lotosu ~ Czerwień i Biel",
    "th155_02": "Mistrzowska Iskra w Kolorze Miłości",
    "th155_03": "Tradycyjny Staruszek i Stylowa Dziewczyna",
    "th155_04": "Czuły Podniebny Żagiel ~ Kosmiczny Umysł",
    "th155_05": "Legenda Wielkich Bogów",
    "th155_06": "Legenda Shoutoku ~ Prawdziwy Administrator",
    "th155_07": "„Kappa” Ryūnosuke Akutagawy ~ Szczera Przyjaciółka",
    "th155_08": "Youkai Dziewczynka Hartmanna",
    "th155_09": "Futatsuiwa z Gensokyo",
    "th155_10": "Utracona Emocja",
    "th155_11": "Sięgaj po Księżyc, Nieśmiertelny Dymie",
    "th155_12": "Kobito Lśniącej Igły ~ Mała Księżniczka",
    "th155_13": "Kwieciste Pole Bitwy",
    "th155_14": "Ostateczny Okultyzm ~ Ezoteryczka Współczesnego Świata",
    "th155_15": "Szalone Oczy ~ Niewidzialna Pełnia Księżyca",
    "th155_16": "Wieczny Wiosenny Sen",
    "th155_17": "Katastrofa w Bhavaagrze ~ Cudowny Raj",
    "th155_18": "Zapada Noc ~ Gwiazda Wieczorna",
    "th155_23": "Stała i Niezmienna Świątynia Uwielbienia",
    "th155_24": "Lśniąca Sfera Armilarna",
    "th155_25": "Postęp Technologiczny Kappy z Wąwozu",
    "th155_27": "W Zielonym Lesie Tanuki",
    "th155_28": "Teatr Shinkirou",
    "th155_30": "Odwrócony Zamek Rozświetlony przez Zachodzące Słońce",
    "th155_32": "Folklor Świata Snów",
    "zsw_05": "Nieskończony Korytarz",
    "th155_33": "Korytarz Ciągnący się przez Wieczność",
    "th155_58": "Wieczna Maszyna Parowa",
    "th165_05": "Bar \"Old Adam\"",
    "th165_06": "Ciemność Spowodowana przez Historię Naturalną",
    "th165_07": "Wieczny Wiosenny Sen",
    "th165_08": "Ukryte Cztery Pory Roku",
    "th03_01": "Sen Wykraczający poza Czasoprzestrzeń",
    "th07_01": "Upiorny Sen ~ Śnieg lub Płatek Wiśni",
    "th07_02": "Raj ~ Głęboka Góra",
    "th07_03": "Skrystalizowane Srebro",
    "th07_04": "Fantastyczne Opowieści z Tōno",
    "th07_05": "Diāo Yè Zōng (zwiędły liść)",
    "th07_08": "Stolica Kwiatów na Niebie",
    "th07_09": "Nawiedzony Zespół ~ Upiorna Kapela",
    "th07_10": "Upiorny Wschodni Sen ~ Starożytna Świątynia",
    "th07_12": "Prawda Ostateczna",
    "th07_14": "Granica Życia",
    "th07_16": "Iluzoryczny Pogrzeb Dziewczyny ~ Nekro-Fantazja",
    "th07_18": "Nekrofantazja",
    "th07_20": "Sakura, Sakura ~ Japoński Sen...",
    "th03_14": "Adoracja Magii",
    "mcd_fairy01_03": "Jak Lśnienie Wróżek",
    "th17_01": "Milczące Zwierzęce Dusze",
    "th17_02": "Lament Znany Tylko Jizo",
    "th17_04": "Zatracona Rzeka",
    "th17_06": "Wieczna Pajęcza Lilia",
    "th17_07": "Seraficki Kurczak",
    "th17_03": "Kamień Meduzy",
    "th17_05": "Kamienne Dziecko i Krowa Pod Wodą",
    "th17_08": "Wszechobecne Piekło",
    "th17_09": "Smoczy Żółw ~ Szczęście i Nieszczęście",
    "th17_10": "Metropolia Bestii",
    "th17_11": "Ceramiczny Joutoujin",
    "th17_12": "Elektryczne Dziedzictwo",
    "th17_13": "Powierzenie Świata Bożkom ~ Uświęcony Świat",
    "th17_14": "Lśniące Prawo Dżungli",
    "th17_15": "Pegaz Księcia Shoutoku ~ Mroczny Pegaz",
    "th17_16": "Spoczynek Zwierząt",
    "th17_17": "Powrót z Podziemi",
    "th135_01": "Niezmienny Pesymizm Nudnego Świata ~ Orkiestra Shinkirou",
    "th135_18": "Zespół Shinkirou",
    "th135_21": "Absolutnie Puste Miejsce",
    "th135_24": "Wybuch Popularności / Reimu Hakurei",
    "th135_25": "Wybuch Popularności / Marisa Kirisame",
    "th135_26": "Wybuch Popularności / Ichirin Kumoi & Unzan",
    "th135_27": "Wybuch Popularności / Byakuren Hijiri",
    "th135_28": "Wybuch Popularności / Mononobe no Futo",
    "th135_29": "Wybuch Popularności / Toyosatomimi no Miko",
    "th135_30": "Wybuch Popularności / Nitori Kawashiro",
    "th135_31": "Wybuch Popularności / Koishi Komeiji",
    "th135_32": "Wybuch Popularności / Mamizou Futatsuiwa",
    "th135_33": "Wybuch Popularności / Hata no Kokoro",
    "th135_34": "Ostatnie Słowo Uwolnione",
    "th145_06": "Starcie Zbieraczy Siedmiu Kul",
    "th145_07": "Nadejście Wiatrów Epoki",
    "th145_08": "Uczciwa Przepychanka",
    "th155_21": "Latający Statek Palanquin",
    "th155_42": "Certyfikat Zgodności",
    "th155_43": "Solidarna Odpowiedzialność",
    "th155_44": "Dziwaczna Para",
    "th155_45": "Działając w Wspólnym Porozumieniu",
    "th155_46": "Przejawy Pompatyczności",
    "th155_47": "Pomysłowo i Zaradnie",
    "th155_48": "Uczucie Triumfalne",
    "th155_49": "Przedstawienie Zaraz Się Zacznie",
    "th155_51": "Nasiona Incydentu",
    "th155_52": "Pączkowanie Podejrzeń",
    "th155_53": "Gałęzie Sięgające Prawdy",
    "th155_54": "Zamieć z Kwiatów Opętania",
    "th155_55": "Płynąc z Prądem",
    "th155_56": "Oczekujące Pąki Kwiatów Opętania",
    "th155_57": "W Pęłni Kwitnący Kwiat Opętania",
    "th17_18": "Wyniki Gracza",
    "th18_18": "Wyniki Gracza",
    "th18_01": "Gensokyo Pokryte Tęczą",
    "th18_02": "Przelotny Deszcz Youkai",
    "th18_03": "Pomyślny Dzień Dla Kociaka",
    "th18_04": "Urwisko Ukryte w Głębokiej Zieleni",
    "th18_05": "Technologia Bandytyzmu",
    "th18_06": "Wieczny Śnieg Kwitnącej Komakusy",
    "th18_07": "Smocza Fajka",
    "th18_08": "Porzucone Resztki Przemysłowe",
    "th18_09": "Ruda z Wieku Bogów",
    "th18_10": "Długo Oczekiwane Oumagatoki",
    "th18_11": "Gwiezdne Niebo Góry Tenmy",
    "th18_12": "Księżyc w Tęczy",
    "th18_13": "Gdzie Jest Teraz Ten Rojny Rynek ~ Odwieczni Marketingowcy",
    "th18_14": "Fantastyczna Sieć Magistral Górniczych",
    "th18_15": "Księżniczka-Pogromczyni Smoczych Króli",
    "th18_16": "Niedziela Po Burzy",
    "th18_17": "Świat w Tęczy",
    "th175_01": "Zanurzone Piekło Tonącej Żałości",
    "th175_02": "Wschodnia Historia Opowieści o Skąpstwie",
    "th175_03": "Prawa Natury i Ludzkości",
    "th175_04": "Melancholia Czarownika",
    "th175_05": "Mroczny Otwór Wentylacyjny",
    "th175_06": "Wędrówka po Ulicach Dawnego Piekła",
    "th175_07": "Płaszcz Piekielnego Ognia",
    "th175_08": "Cmentarz Onbashiry ~ Grób Istnienia",
    "th175_09": "Otchłań Ziemi, Morze Skąpstwa",
    "th175_10": "Wieczna Pajęcza Lilia",
    "th175_11": "Cowieczna Uroczystość Magicznych Dziewcząt",
    "th175_12": "Dziewczęcy Kaprys ~ Wojna Snu",
    "th175_13": "Mistrzowska Iskra w Kolorze Miłości",
    "th175_14": "Zapieczętowany Youkai ~ Utracone Miejsce",
    "th175_15": "Uważajcie na Parasolkę Pozostawioną Tu na Wieki",
    "th175_16": "Kapitan Murasa",
    "th175_17": "Sędziwe Starożytne Pole Bitwy ~ Pole Wojenne w Suwie",
    "th175_18": "Gwiazdą Wieczoru jest Swobodna Egoistka ~ Kwiaty Egoizmu",
    "th175_19": "Wysadzane Kwiatami Naczynie Do Sake Góry Ooe",
    "th175_20": "Słoneczna Sekta Mistycznej Wiedzy ~ Synteza Jądrowa",
    "th175_21": "Seraficki Kurczak",
    "th175_22": "U.N. Owen to Ona?",
    "th175_23": "Pamiątka Chciwej Bestii",
    "th175_24": "Pamiątka Wszystkich Ciał Organicznych ~ Wspomnienie Mocy Skamienin",
    "mcd_095_01": "Wilk z Nanatsuishi Biegnie Po Chmurach",
    "mcd_095_02": "Iluzoryczny Biały Podróżnik",
    "mcd_095_03": "Gdzie Jest Teraz Ten Rojny Rynek ~ Odwieczni Marketingowcy",
    "th185_01": "Melancholijne Popołudnie Kolekcjonera",
    "th185_02": "Ekscytująca Znajoma Kraina Fantazji",
    "th185_03": "Zaczepienie Potwora",
    "th185_04": "Czarny Rynek Jest Wszędzie",
    "th185_05": "Weźcie Swój Ogień w Ręce, Pociskofile",
    "th185_06": "Setny Czarny Rynek",
    "th185_07": "Szalony Marzyciel",
    "th185_08": "Księżyc w Tęczy",
    "th185_09": "Gdzie Jest Teraz Ten Rojny Rynek ~ Odwieczni Marketingowcy",
    "th185_10": "Świat w Tęczy",
    "mcd_01_04": "Alicja z Szanghaju roku Meiji 17",
    "th01_05": "Dziwna Dysputa Wschodu",
    "mcd_01_05": "Dziwna Dysputa Wschodu",
    "tmgc_01": "Czarownica Eliksiru Miłości",
    "mcd_01_09": "Czarownica Eliksiru Miłości",
    "mcd_01_11": "U.N. Owen to Ona?",
    "th01_02": "Wieczna Kapłanka",
    "mcd_01_12": "Wieczna Kapłanka",
    "mcd_02_03": "Upiorny Wschodni Sen ~ Starożytna Świątynia",
    "th075_13": "Upiorny Wschodni Sen ~ Starożytna Świątynia",
    "sh01_11": "Krucjata Magicznych Dziewczynek",
    "mcd_02_09": "Krucjata Magicznych Dziewczynek",
    "mcd_02_10": "Iluzoryczny Pogrzeb Dziewczyny ~ Nekro-Fantazja",
    "mcd_02_05": "Iluzjonistyczna Noc ~ Upiorne Oczy",
    "th08_02": "Iluzjonistyczna Noc ~ Upiorne Oczy",
    "th075_02": "Wschodnie Mistyczne Konsultacje Miłosne",
    "th04_10": "Dziewczęcy Kaprys",
    "th075_03": "Dziewczęcy Kaprys",
    "th075_04": "Magia w Kolorze Miłości",
    "th075_06": "Pokojówka i Kieszonkowy Zegarek Krwi",
    "th075_07": "Zegar Księżycowy ~ Cyferblat Księżyca",
    "th075_08": "Lalkarz z Bukaresztu",
    "th075_10": "Zamknięta Dziewczyna ~ Zamknięty Pokój Dziewczyny",
    "mcd_04_09": "Zamknięta Dziewczyna ~ Zamknięty Pokój Dziewczyny",
    "th075_11": "Voile, Magiczna Biblioteka",
    "th075_12": "Hiroari Strzela do Tajemniczego Ptaka ~ Do Kiedy?",
    "th075_14": "Septet dla Martwej Księżniczki",
    "th075_15": "Kwitnij Szlachetnie, Tuszo-Czarny Kwiecie Wiśni ~ Granica Życia",
    "mcd_03_03": "Szkarłatna Szanghajska Herbaciarnia ~ Chińska Herbata",
    "th08_13": "Wojaż 1969",
    "mcd_03_04": "Wojaż 1969",
    "mcd_03_06": "Zemsta za Wieczną Noc ~ Nieprzemijająca Noc",
    "mcd_03_07": "Zapada Noc ~ Gwiazda Wieczorna",
    "mcd_03_08": "Sąd Lalek ~ Dziewczynka, Która Bawiła się Formami Ludzi",
    "mcd_baijr_01": "Młoda Bogini Wiatru",
    "th095_06": "Młoda Bogini Wiatru",
    "mcd_baijr_02": "Przygody Zakochanej Chłopczycy",
    "th08_15": "Lot Zbieracza Bambusu ~ Szalona Księżniczka",
    "mcd_04_03": "Lot Zbieracza Bambusu ~ Szalona Księżniczka",
    "mcd_04_04": "Do Higan i z Powrotem ~ Nadrzeczny Krajobraz",
    "mcd_04_06": "Biała Flaga Czcigodnego Pana Usy",
    "mcd_04_07": "Sięgaj po Księżyc, Nieśmiertelny Dymie",
    "th095_05": "Retrospektywne Kyoto",
    "mcd_04_08": "Retrospektywne Kyoto",
    "th08_14": "Millenium Gensokyo ~ Historia Księżyca",
    "mcd_04_10": "Millenium Gensokyo ~ Historia Księżyca",
    "th095_04": "Bezsenna Noc Wschodniego Kraju",
    "mcd_05_03": "Bezsenna Noc Wschodniego Kraju",
    "th075_16": "Wyjaśnić Ucztę",
    "mcd_05_05": "Wyjaśnić Ucztę",
    "mcd_05_09": "Nekrofantazja",
    "mcd_scoow05_03": "Nekrofantazja",
    "th11_18": "Wyniki Gracza",
    "th12_18": "Wyniki Gracza",
    "th13_18": "Wyniki Gracza",
    "mcd_fairy03_03": "Nie Zasnę z Powodu Nocy",
    "mcd_fairy03_04": "Jak Lśnienie Wróżek",
    "sh01_08": "Złudna Noc Sputnika",
    "mcd_gom_02": "Złudna Noc Sputnika",
    "mcd_055_03": "Jutro Będzie Wyjątkowe, Wczoraj Nie Było",
    "th125_06": "Góra Youkai ~ Tajemnicza Góra",
    "mcd_fairy05_02": "Nowoczesna Kolonia Youkai",
    "mcd_fairy03_01": "Przyśpiew Przepięknej Wielkiej Wojny",
    "mcd_fairy06_01": "Ciekawość Pochłonięta z Całego Roku",
    "mcd_fairy06_02": "Taniec Wróżek o Północy",
    "mcd_fairy06_03": "Wielkie Wojny Wróżek ~ Wojny Wróżek",
    "th125_05": "Dzwon Avici ~ Niekończący się Koszmar",
    "mcd_055_02": "Dzwon Avici ~ Niekończący się Koszmar",
    "mcd_fairy07_01": "Noc Magów",
    "mcd_fairy07_02": "Ryzykując Swym Życiem Dla Żartu",
    "mcd_fairy07_03": "Stary Odległy Pustelnik",
    "mcd_06_03": "Popęd Pragnień",
    "mcd_06_04": "Przygody Wróżek",
    "mcd_06_06": "Romans z UFO na Nocnym Niebie",
    "mcd_06_07": "Youkai Dziewczynka Hartmanna",
    "mcd_06_09": "Czuły Podniebny Żagiel ~ Kosmiczny Umysł",
    "mcd_07_03": "Zachcianka z Głębi Serca",
    "mcd_07_04": "Wschodni Sąd Sześćdziesiątego Roku ~ Los Sześćdziesięciu Lat",
    "mcd_07_07": "Droga Youkai za Świątynią",
    "mcd_07_08": "Nieznane X ~ Nieodkryta Przygoda",
    "mcd_07_10": "Zamieszkajmy na Uroczym Cmentarzu",
    "mcd_scoow02_01": "Przyciąganie Okultystycznego",
    "th155_38": "Przyciąganie Okultystycznego",
    "mcd_scoow02_03": "Ostateczny Okultyzm ~ Ezoteryczka Współczesnego Świata",
    "mcd_09_09": "Wybuch Popularności / Ichirin Kumoi & Unzan",
    "mcd_fs_02": "Ludzie i Youkai Przemierzający Kanał",
    "mcd_fs_03": "Królik Wylądował",
    "mcd_03_01": "Festiwal Dzieci ~ Niewinne Skarby",
    "mcd_scoow03_01": "Festiwal Dzieci ~ Niewinne Skarby",
    "mcd_scoow03_02": "Jezioro Mgły",
    "mcd_scoow03_03": "Lemuria Pijaka",
    "th155_39": "Neo Bambusowy Las w Ogniu",
    "th155_40": "Dzwon Eonów",
    "mcd_gom_01": "Melancholia Czarownika",
    "th08_09": "Dziewczęcy Kaprys ~ Wojna Snu",
    "th19_04": "Para Boskich Bestii",
    "th19_05": "Pod Koniec Wiosny",
    "th19_06": "Niezapomniana Nostalgiczna Zieleń",
    "mcd_fairy01_01": "Słoneczna Odmiana Rutylu",
    "mcd_fairy03_02": "Słoneczna Odmiana Rutylu",
    "mcd_scoow01_01": "Noworoczne Kwitnienie Wiśni",
    "mcd_scoow01_02": "Izolator",
    "mcd_scoow01_03": "PLAIN ASIA (2015 ALR REWIND REMIX)",
    "mcd_scoow02_02": "Zemsta Wiecznej Nocy ~ Rury i Machlojki",
    "mcd_09_04": "Obcy Koktajl",
    "mcd_09_10": "Kac Inaczej Śniących Współlokatorów",
    "mcd_fs_01": "Bibliofilia Czytającego Oka",
    "mcd_scoow04_01": "Żniwo Które Krąży Wokół",
    "mcd_scoow04_02": "Bezduszna Powierzchnia",
    "mcd_scoow04_03": "Rzeczywistość Końca I Przeszłości",
    "mcd_scoow05_01": "Cyklonowa Keyboardzistka",
    "mcd_scoow05_02": "Śniąca Dziewczynka Hartmanna",
    "th19_01": "Naturoznawcza Bestia",
    "th19_02": "Świat Publiki który Powinien Kochać Wychodzić",
    "th19_03": "Scramblujące Złe Duchy",
    "none": "(brak)",
    "th05_01": "Niezwykłe Romantyczne Baśnie ~ Kwadrat Mistyczny",
    "th05_03": "Kwadrat Magiczny",
    "th03_11": "Decydująca Magiczna Bitwa! ~ Czas się zmierzyć!",
    "th08_01": "Urywek Wiecznej Nocy ~ Wschodnia Noc",
    "th08_04": "Pieśń Nocnego Wróbla ~ Nocny Ptak",
    "th08_06": "Nostalgiczna Krew Wschodu ~ Stary Świat",
    "th08_07": "Szczera Azja",
    "th08_11": "Klatka Kopciuszka ~ Kagome-Kagome",
    "th08_16": "Wojaż 1970",
    "th08_19": "Wiesiołek",
    "th08_20": "Wieczny Sen ~ Mistyczny Klon",
    "th19_10": "Starożytny Krajobraz Japonii Widziany przez Dziewczynkę",
    "th19_17": "Futatsuiwa z Sado",
    "th19_11": "Niepohamowane Dusze ~ Kto to Zrobił!",
    "th19_12": "Para Boskich Bestii",
    "th19_13": "W Przystani Wiosny",
    "th19_14": "Niezapomniana Nostalgiczna Zieleń",
    "th19_15": "Podróż Truposzy ~ Raduj się!",
    "th19_16": "Długo Oczekiwane Oumagatoki",
    "th19_18": "Smoczy Żółw ~ Szczęście i Nieszczęście",
    "th19_20": "Pamiątka Chciwej Bestii",
    "th19_19": "Pegaz Księcia Shoutoku ~ Mroczny Pegaz",
    "mcd_baijr_03": "Kurhan Odzwierciedlający Kwiaty ~ Po Powrocie z Higan",
    "th05_18": "Chram Sintoizmu",
    "th01_15": "Chram Wiatru",
    "th02_16": "Ziemie Chramu Hakurei",
    "th095_01": "Notatnik Tengu ~ Tajemniczy Zapis",
    "th095_02": "Krążenie Powietrza ~ Podróż Wiatru",
    "th095_03": "Tengu Obserwuje ~ Czarne Oczy",
    "th075_09": "Sąd Lalek",
    "th075_20": "Wschodnie Gromadzone Marzenie",
    "th075_24": "Wnętrze Umysłu",
    "th075_28": "Obserwator Nieba",
    "th125_01": "Łowca Sensacji",
    "th125_02": "Tajemnica Twojego Miasteczka",
    "th125_04": "Warownia Nemezis",
    "mcd_scoow06_03": "Nekrofantazja",
    "mcd_10_10": "Ukryte Cztery Pory Roku",
    "mcd_10_03": "Czy Zakazane Drzwi Prowadzą do Tego Świata, Czy Następnego?",
    "mcd_10_04": "Smocza Fajka",
    "mcd_10_06": "Szalone Tancerki Drugiego Planu",
    "mcd_10_07": "Yorimashi Między Snem a Rzeczywistością ~ Nekrofantazja",
    "mcd_10_09": "Lament Znany Tylko Jizo"
}